classDiagram
    class File {
        -String fileId
        -String name
        -long size
    }
    class Directory {
        -String directoryId
        -String name
    }
    class FileSystem {
        -Directory root
        +createFile()
    }
    FileSystem --> Directory
    Directory --> File
