classDiagram
    class Logger {
        -String name
        -LogLevel level
        +log()
        +debug()
        +info()
        +error()
    }
    class Appender {
        <<interface>>
        +append()
    }
    class FileAppender {
        +append()
    }
    class ConsoleAppender {
        +append()
    }
    Logger --> Appender
    Appender <|.. FileAppender
    Appender <|.. ConsoleAppender
