classDiagram
    class TrafficLight {
        -String lightId
        -LightStatus status
    }
    class Intersection {
        -String intersectionId
    }
    class TrafficControlService {
        <<interface>>
        +updateSignal()
    }
    TrafficControlService --> Intersection
    Intersection --> TrafficLight
