classDiagram
    class BloomFilter {
        -BitSet bitSet
        -int size
        -List~HashFunction~ hashFunctions
        +add()
        +mightContain()
    }
    class HashFunction {
        <<interface>>
        +hash() int
    }
    BloomFilter --> HashFunction
