classDiagram
    class Card {
        -String cardNumber
    }
    class Account {
        -String accountId
        -double balance
    }
    class ATM {
        -String atmId
        +withdraw()
        +deposit()
    }
    ATM --> Card
    ATM --> Account
