classDiagram
    class Topic {
        -String topicId
        -String name
    }
    class Message {
        -String messageId
        -String content
    }
    class Subscription {
        -String subscriptionId
    }
    class PubSubService {
        <<interface>>
        +createTopic()
        +publish()
    }
    PubSubService --> Topic
    PubSubService --> Message
    PubSubService --> Subscription
