# ai_systems_content_p2.py — topics 4-11

# ── 4. tool-calling-functions ───────────────────────────────────────
TOPICS["tool-calling-functions"] = dict(
    title="Tool Calling & Functions",
    nav="Tool Calling",
    hero="LLM function calling: JSON schema design, tool registry, execution sandbox, parallel calls, error recovery. The bridge between reasoning and the real world.",
    tags=_tags(("JSON Schema", ""), ("Sandbox", " orange"), ("Parallel", " green"), ("Validation", " pink"), ("OpenAI", " blue")),
    main_img="tool-calling-functions-main.png",
    main_cap="Tool calling loop: LLM receives tool schemas, emits tool_calls JSON, executor runs in sandbox, results appended to messages, loop until final answer.",
    nav_items=_nav(("01","whatwhy","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),("02","whento","When to Use"),("03","architecture","Architecture"),("04","schema","Schema Design"),("05","registry","Tool Registry"),("06","sandbox","Execution Sandbox"),("07","errors","Error Handling"),("08","parallel","Parallel Tools"),("09","production","Production & Ops"),("10","shows-up","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A")),
    sections=[
        ("whatwhy","01","What & Why", card("<p>Tools let LLMs query databases, call APIs, run code. Schema is the contract; executor is the trust boundary.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),(("td","Tool schema"),("td","JSON Schema describing params"),("td","Vague descriptions = bad args")),(("td","tool_calls"),("td","LLM output requesting function execution"),("td","Validate before execute")),(("td","tool_choice"),("td","auto | required | none"),("td","required forces tool even when unnecessary")),]))),
        ("api","01b","API Surface", card('<pre>tools=[{"type":"function","function":{\n  "name":"search_docs",\n  "description":"Search internal KB",\n  "parameters":{"type":"object","properties":{\n    "query":{"type":"string","description":"Search query"}\n  },"required":["query"]}\n}}]\nresponse = client.chat.completions.create(model="gpt-4o", messages=msgs, tools=tools)</pre>')),
        ("whento","02","When to Use / When NOT", card(tbl([(("th","Approach"),("th","Use When"),("th","Skip When")),(("td","Function calling"),("td","Structured API/DB access"),("td","Answer in context already")),(("td","Code interpreter"),("td","Data analysis, plotting"),("td","Untrusted user input without sandbox")),]))),
        ("architecture","03","Architecture", card('<pre>LLM -> tool_calls[] -> Validator -> Executor (sandbox) -> tool results -> LLM loop</pre>')),
        ("schema","04","Deep Dive: Schema Design", diag("tool-calling-functions","schema-zoom","JSON schema fields: name, description, parameters with types and enums") + card("<p>Descriptions are prompts. Use enums for finite choices. Required fields only. Example values in description.</p>")),
        ("registry","05","Deep Dive: Tool Registry", card("<p>Central registry maps name → handler + schema + ACL. Dynamic registration per tenant. Max 20 tools per call — prune by relevance classifier.</p>")),
        ("sandbox","06","Deep Dive: Execution Sandbox", card("<p>Network egress allowlist. Read-only DB creds. Timeout 30s. No filesystem write except /tmp. Firecracker/gVisor for code execution.</p>")),
        ("errors","07","Deep Dive: Error Handling", card("<p>Return structured errors to LLM: {error, retry_hint}. Max 3 retries per tool. Circuit breaker on downstream failures.</p>")),
        ("parallel","08","Deep Dive: Parallel Tools", diag("tool-calling-functions","loop-zoom","LLM emits parallel tool_calls; executor runs concurrently; results merged") + card("<p>OpenAI parallel tool_calls. asyncio.gather for independent searches. Sequential when tool B needs tool A output.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Log every tool call: name, args, latency, success</li><li>PII scrubbing on args before log</li><li>Rate limit per tool per user</li></ul>")),
        ("shows-up","10","Where It Shows Up", card('<ul><li><a href="agent-architectures.html">Agent Architectures</a></li><li><a href="production-agent.html">Production Agent</a></li><li><a href="../tech/langgraph.html">LangGraph</a></li><li><a href="../fundamentals/prompt-engineering.html">Prompt Engineering</a></li></ul>')),
        ("pitfalls","11","Common Pitfalls", card("<ul><li>20+ tools confuses model — use retrieval over tools</li><li>Executing unvalidated args (SQL injection)</li><li>No timeout on tool execution</li><li>Returning huge raw JSON to context</li></ul>")),
    ],
    qa=_qa(
        ("How design a good tool schema?", "Clear name, action-oriented description, typed params with descriptions, enums for choices, minimal required fields, example in description."),
        ("tool_choice auto vs required?", "auto: model decides. required: forces tool call every turn — use when always need retrieval. none: disable tools."),
        ("How prevent SQL injection from tool args?", "Parameterized queries only. Validate args against schema. Read-only DB user. Never string-concat SQL from LLM output."),
        ("Parallel vs sequential tool calls?", "Parallel when independent (search 3 sources). Sequential when dependent (get_user then get_orders)."),
        ("What return on tool failure?", "Structured error JSON with retry_hint. Let LLM recover. Don't throw opaque 500 to model."),
        ("How limit tool count?", "Dynamic tool retrieval: embed query, select top-5 relevant tools from registry of 100+."),
        ("Sandbox requirements for code exec?", "No network by default, CPU/memory limits, timeout, ephemeral filesystem, audit log."),
        ("Anthropic vs OpenAI tool format?", "Both JSON schema; Anthropic tool_use blocks vs OpenAI tool_calls. Normalize in adapter layer."),
        ("How test tools?", "Unit test handlers. Integration test full loop with mocked LLM. Golden trajectories for agent regressions."),
        ("Idempotent tools?", "Design GET-like tools idempotent. Write tools need confirmation/HITL and idempotency keys."),
        ("Tool result size limits?", "Truncate/summarize large results before appending to messages. Store full result externally; pass reference."),
        ("SDE3: tool platform for 200 internal APIs?", "Registry with OpenAPI import, auto-schema, per-team ACL, sandbox executor, unified tracing, HITL gate on write tools."),
    ),
)

# ── 5. agent-memory ─────────────────────────────────────────────────
TOPICS["agent-memory"] = dict(
    title="Agent Memory",
    nav="Agent Memory",
    hero="Short-term scratchpad, long-term vector store, episodic summaries, and consolidation. Agents need memory — but unbounded context is not memory.",
    tags=_tags(("Scratchpad", ""), ("Vector Memory", " orange"), ("Episodic", " green"), ("Summarize", " pink"), ("TTL", " blue")),
    main_img="agent-memory-main.png",
    main_cap="Agent memory layers: in-context scratchpad (current turn), session buffer (summarized history), long-term vector memory (user facts), episodic log (past task outcomes).",
    nav_items=_nav(("01","whatwhy","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),("02","whento","When to Use"),("03","architecture","Architecture"),("04","scratchpad","Scratchpad"),("05","longterm","Long-Term Vector"),("06","episodic","Episodic"),("07","consolidation","Consolidation"),("08","retrieval","Memory Retrieval"),("09","production","Production & Ops"),("10","shows-up","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A")),
    sections=[
        ("whatwhy","01","What & Why", card("<p>Agents need prior context across turns and sessions. Memory systems trade recall fidelity vs token cost vs latency.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),(("td","Scratchpad"),("td","Current reasoning + tool results in context"),("td","Grows unbounded without pruning")),(("td","Semantic memory"),("td","Embedded facts retrievable by similarity"),("td","Stale facts without TTL")),(("td","Episodic memory"),("td","Past task trajectories and outcomes"),("td","Privacy: user data isolation")),]))),
        ("api","01b","API Surface", card('<pre>memory.store(user_id, text, metadata={type:"preference"})\nmemory.search(user_id, query, top_k=5) -> memories[]\nmemory.summarize(session_id) -> summary  # compress buffer</pre>')),
        ("whento","02","When to Use / When NOT", card(tbl([(("th","Type"),("th","Use When"),("th","Skip When")),(("td","Full history"),("td","Short sessions &lt;10 turns"),("td","Long chats — exceeds context")),(("td","Vector memory"),("td","User prefs, facts across sessions"),("td","Single-turn Q&A")),]))),
        ("architecture","03","Architecture", card('<pre>Turn -> Scratchpad -> [if tokens > budget] Summarize -> Long-term store (embed)\nQuery -> Retrieve relevant memories -> Inject into system prompt</pre>')),
        ("scratchpad","04","Deep Dive: Scratchpad", card("<p>Working memory: thoughts, tool JSON, observations. Truncate old observations; keep last 3 tool results full.</p>")),
        ("longterm","05","Deep Dive: Long-Term Vector Memory", diag("agent-memory","vector-zoom","User facts embedded and stored in vector DB; retrieved by query similarity at session start") + card("<p>Mem0, Zep, custom pgvector. Store extracted facts not raw chat. user_id namespace isolation.</p>")),
        ("episodic","06","Deep Dive: Episodic Memory", card("<p>Log (task, plan, outcome, success). Retrieve similar past tasks when user asks repeat workflow.</p>")),
        ("consolidation","07","Deep Dive: Consolidation", diag("agent-memory","consolidation-zoom","Session end: LLM extracts durable facts, discards ephemeral tool noise, writes to long-term store") + card("<p>End-of-session job: extract preferences, delete contradictions, TTL on time-sensitive facts.</p>")),
        ("retrieval","08","Deep Dive: Memory Retrieval", card("<p>At session start: embed user message, search memory top-5, inject as system context. Re-rank by recency × relevance.</p>")),
        ("production","09","Production & Ops", card("<ul><li>GDPR delete by user_id across memory stores</li><li>Don't store secrets/PII without encryption</li><li>Memory write audit log</li></ul>")),
        ("shows-up","10","Where It Shows Up", card('<ul><li><a href="agent-architectures.html">Agent Architectures</a></li><li><a href="production-agent.html">Production Agent</a></li><li><a href="../tech/vector-databases.html">Vector Databases</a></li><li><a href="semantic-cache.html">Semantic Cache</a></li></ul>')),
        ("pitfalls","11","Common Pitfalls", card("<ul><li>Dumping full chat history — context overflow</li><li>Storing contradictory facts without merge</li><li>Cross-user memory leakage</li><li>No TTL on outdated preferences</li></ul>")),
    ],
    qa=_qa(
        ("Scratchpad vs long-term memory?", "Scratchpad: current task working state in context. Long-term: persisted facts across sessions retrieved by embedding similarity."),
        ("When summarize vs retrieve?", "Summarize when session exceeds token budget. Retrieve when need specific past facts not in recent buffer."),
        ("How extract facts for storage?", "LLM extraction prompt at session end: list durable user preferences/facts. Discard tool noise and ephemeral data."),
        ("Memory privacy?", "Strict user_id namespace. Encrypt at rest. Delete API for GDPR. Never cross-tenant retrieval."),
        ("Mem0 vs Zep vs roll-your-own?", "Mem0/Zep: managed memory layers. Roll-your-own pgvector if need full control and existing stack."),
        ("How handle contradictory memories?", "Store timestamp + source. On conflict, prefer newer or ask user. Consolidation job merges duplicates."),
        ("Episodic memory use case?", "User: 'do what I did last Tuesday' — retrieve similar task trajectory and replay adapted plan."),
        ("Token budget for memory injection?", "Cap retrieved memories at 500–1000 tokens. Top-5 facts usually sufficient."),
        ("Reflexion vs episodic?", "Reflexion: critique within same task retry. Episodic: store outcome for future different tasks."),
        ("Memory for multi-agent?", "Shared blackboard for task state; per-agent private scratchpad. Long-term memory at user level not agent level."),
        ("Eval memory quality?", "Recall: does agent remember stated preference 10 turns later? Precision: no hallucinated memories injected."),
        ("SDE3: memory architecture for support bot?", "Session buffer with rolling summary. Vector memory for account prefs. Episodic for resolved ticket patterns. TTL 90 days. GDPR purge API."),
    ),
)

# ── 6. rlhf-dpo-pipeline ────────────────────────────────────────────
TOPICS["rlhf-dpo-pipeline"] = dict(
    title="RLHF & DPO Pipeline",
    nav="RLHF / DPO",
    hero="Align LLMs with human preferences: SFT baseline, reward modeling, PPO/RLHF, DPO direct preference optimization. Know when alignment training beats prompt engineering.",
    tags=_tags(("SFT", ""), ("Reward Model", " orange"), ("DPO", " green"), ("PPO", " pink"), ("Alignment", " blue")),
    main_img="rlhf-dpo-pipeline-main.png",
    main_cap="Alignment pipeline: base model → SFT on demonstrations → preference pair collection → DPO or RLHF (reward model + PPO) → aligned model → eval harness gate.",
    nav_items=_nav(("01","whatwhy","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),("02","whento","When to Use"),("03","architecture","Architecture"),("04","sft","SFT Baseline"),("05","reward","Reward Model"),("06","dpo","DPO"),("07","ppo","PPO / RLHF"),("08","eval","Alignment Eval"),("09","production","Production & Ops"),("10","shows-up","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A")),
    sections=[
        ("whatwhy","01","What & Why", card("<p>Base LLMs optimize next-token prediction, not helpfulness or safety. Alignment training steers behavior toward human preferences.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),(("td","SFT"),("td","Supervised fine-tune on expert demos"),("td","Imitates demos not preferences")),(("td","Reward model"),("td","Scores response quality"),("td","Goodharting — optimize score not intent")),(("td","DPO"),("td","Direct preference optimization without RM"),("td","Needs quality preference pairs")),(("td","PPO"),("td","RL fine-tune against reward model"),("td","Unstable, expensive")),]))),
        ("api","01b","API Surface", card('<pre># Preference dataset format\n{"prompt": "...", "chosen": "...", "rejected": "..."}\n\n# TRL DPO\ntrainer = DPOTrainer(model, ref_model, train_dataset=prefs)\ntrainer.train()</pre>')),
        ("whento","02","When to Use / When NOT", card(tbl([(("th","Method"),("th","Use When"),("th","Skip When")),(("td","Prompt only"),("td","General assistant behavior"),("td","Need domain-specific tone at scale")),(("td","DPO/LoRA"),("td","Preference data available, moderate shift"),("td","No preference labels")),(("td","Full RLHF"),("td","Large budget, research-grade alignment"),("td","Most product teams — use DPO")),]))),
        ("architecture","03","Architecture", card('<pre>Base LM -> SFT -> Collect prefs (A/B human rank) -> DPO train -> Eval gate -> Deploy</pre>')),
        ("sft","04","Deep Dive: SFT Baseline", card("<p>10K–100K high-quality (prompt, response) pairs. Must precede DPO. Teaches format and domain vocabulary.</p>")),
        ("reward","05","Deep Dive: Reward Model", diag("rlhf-dpo-pipeline","reward-zoom","Reward model scores chosen response higher than rejected; Bradley-Terry loss") + card("<p>Train classifier on preference pairs. Used as PPO reward signal. Monitor reward hacking.</p>")),
        ("dpo","06","Deep Dive: DPO", diag("rlhf-dpo-pipeline","dpo-zoom","DPO loss directly increases log-prob of chosen vs rejected without separate reward model") + card("<p>DPO is default for most teams: simpler than PPO, no reward model, stable on 7B–70B with LoRA.</p>")),
        ("ppo","07","Deep Dive: PPO / RLHF", card("<p>PPO fine-tunes policy against RM with KL penalty to base model. OpenAI original InstructGPT path. Expensive and unstable — reserved for frontier labs.</p>")),
        ("eval","08","Deep Dive: Alignment Eval", card("<p>Win-rate vs baseline on held-out prefs. Safety red-team set. Capability eval (don't degrade MMLU). MT-Bench / Arena Elo.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Version alignment dataset with model</li><li>A/B aligned vs base in shadow</li><li>Monitor refusal rate and user thumbs</li></ul>")),
        ("shows-up","10","Where It Shows Up", card('<ul><li><a href="fine-tuning-lora.html">Fine-Tuning LoRA</a></li><li><a href="eval-harness.html">Eval Harness</a></li><li><a href="../fundamentals/llm-fundamentals.html">LLM Fundamentals</a></li><li><a href="production-agent.html">Production Agent</a></li></ul>')),
        ("pitfalls","11","Common Pitfalls", card("<ul><li>DPO without SFT baseline</li><li>Preference data from single annotator bias</li><li>Reward hacking / sycophancy</li><li>Alignment tax on reasoning capability</li></ul>")),
    ],
    qa=_qa(
        ("RLHF vs DPO?", "RLHF: train reward model + PPO — complex, unstable. DPO: optimize preferences directly — simpler, default for product teams with LoRA."),
        ("What data for DPO?", "Triplets: prompt, chosen response, rejected response. 5K–50K pairs. Diverse prompts; consistent ranking criteria."),
        ("Why SFT before DPO?", "SFT teaches format and domain. DPO refines preferences on top. DPO alone on base model often fails to learn task format."),
        ("What is reward hacking?", "Model optimizes RM score without being actually helpful — verbose, sycophantic answers. Mitigate with KL penalty and human eval."),
        ("PPO when still used?", "Frontier labs with compute for online RL. Most enterprises use DPO or RLHF-DPO hybrid (Constitutional AI)."),
        ("How eval alignment?", "Preference win-rate on held-out set. Safety benchmarks. Regression on capability evals. Production thumbs up/down."),
        ("Alignment tax?", "Alignment can slightly reduce raw reasoning scores. Monitor MMLU/GSM8K during training; early stop if >3% drop."),
        ("Human preference collection?", "Side-by-side ranking UI. Multiple annotators. Inter-rater agreement >0.7. Balance easy/hard prompts."),
        ("DPO + LoRA?", "Standard stack: QLoRA on 7B–70B with preference pairs. Train on 1–4 A100s for hours not weeks."),
        ("Constitutional AI?", "AI generates critique/revision against principles. Reduces human label need. Used in Claude training pipeline."),
        ("Online vs offline RL?", "Offline: DPO on fixed prefs. Online: PPO with live RM — higher risk, used at scale by OpenAI."),
        ("SDE3: alignment plan for domain assistant?", "Month 1: SFT on 20K expert pairs. Month 2: collect 10K prefs from PM review. Month 3: DPO LoRA. Eval gate: win-rate >60% + no safety regression. Shadow deploy."),
    ),
)

# ── 7. eval-harness ─────────────────────────────────────────────────
TOPICS["eval-harness"] = dict(
    title="Eval Harness & Golden Sets",
    nav="Eval Harness",
    hero="Golden datasets, automated metrics, regression gates, and human eval loops. You cannot improve what you do not measure — especially for non-deterministic LLM outputs.",
    tags=_tags(("Golden Set", ""), ("Ragas", " orange"), ("Regression", " green"), ("LLM Judge", " pink"), ("CI Gate", " blue")),
    main_img="eval-harness-main.png",
    main_cap="Eval harness: golden Q&A dataset, retrieval metrics, generation metrics (faithfulness, relevance), CI regression gate, human spot-check queue, production feedback loop.",
    nav_items=_nav(("01","whatwhy","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),("02","whento","When to Use"),("03","architecture","Architecture"),("04","golden","Golden Sets"),("05","retrieval","Retrieval Metrics"),("06","generation","Generation Metrics"),("07","llmjudge","LLM-as-Judge"),("08","ci","CI Regression Gate"),("09","production","Production & Ops"),("10","shows-up","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A")),
    sections=[
        ("whatwhy","01","What & Why", card("<p>LLM outputs are stochastic. Eval harness provides reproducible quality measurement across prompt, model, and retrieval changes.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),(("td","Golden set"),("td","Human-labeled Q&A with expected sources"),("td","Must be held-out from tuning")),(("td","Faithfulness"),("td","Answer supported by context"),("td","LLM judge can be biased")),(("td","Regression gate"),("td","Block deploy if metric drops"),("td","Flaky judges cause false blocks")),]))),
        ("api","01b","API Surface", card('<pre>POST /v1/eval/run\n  { suite: "rag-golden-v3", config: { model, retriever, prompt_v } }\n  -> { recall_at_5, faithfulness, latency_p99, pass: true }\n\n# Ragas\nfrom ragas import evaluate\nresults = evaluate(dataset=golden, metrics=[faithfulness, answer_relevancy])</pre>')),
        ("whento","02","When to Use / When NOT", card(tbl([(("th","Eval type"),("th","Use When"),("th","Skip When")),(("td","Golden set"),("td","Every RAG/agent deploy"),("td","Exploratory prototype only")),(("td","LLM judge"),("td","Scale beyond manual review"),("td","High-stakes legal — need human")),(("td","A/B online"),("td","Post-launch optimization"),("td","Pre-launch baseline missing")),]))),
        ("architecture","03","Architecture", card('<pre>Golden Set -> Eval Runner -> [Retrieval metrics | Generation metrics]\n              -> Report -> CI Gate (pass/fail) -> Human review queue</pre>')),
        ("golden","04","Deep Dive: Golden Sets", diag("eval-harness","golden-zoom","Golden set structure: question, gold_answer, gold_chunk_ids, difficulty tag, tenant") + card("<p>200–500 pairs minimum. Tags: easy/medium/hard, single-hop/multi-hop. Synthetic bootstrap; human label source of truth.</p>")),
        ("retrieval","05","Deep Dive: Retrieval Metrics", card("<p>Recall@k, MRR, nDCG@k. Requires gold_chunk_ids per question. Run on every index/chunk change.</p>")),
        ("generation","06","Deep Dive: Generation Metrics", card("<p>Faithfulness, answer relevance, context precision/recall. Ragas, DeepEval, Phoenix.</p>")),
        ("llmjudge","07","Deep Dive: LLM-as-Judge", diag("eval-harness","judge-zoom","GPT-4 judge scores faithfulness 1-5 with rubric and chain-of-thought reasoning") + card("<p>Use stronger model as judge. Rubric in prompt. Correlate judge with human labels monthly.</p>")),
        ("ci","08","Deep Dive: CI Regression Gate", card("<p>Block merge if Recall@5 drops >2% or faithfulness drops >5%. Run on PR with smaller smoke set (50 cases).</p>")),
        ("production","09","Production & Ops", card("<ul><li>Weekly human spot-check 50 production queries</li><li>Thumbs down → auto-add to review queue</li><li>Eval dashboard per model version</li></ul>")),
        ("shows-up","10","Where It Shows Up", card('<ul><li><a href="rag-end-to-end.html">RAG End-to-End</a></li><li><a href="rlhf-dpo-pipeline.html">RLHF & DPO</a></li><li><a href="production-agent.html">Production Agent</a></li><li><a href="../fundamentals/prompt-engineering.html">Prompt Engineering</a></li></ul>')),
        ("pitfalls","11","Common Pitfalls", card("<ul><li>Eval leakage — golden Q derived from dev chunks</li><li>Single metric optimization</li><li>Flaky LLM judge without calibration</li><li>No eval before prompt change</li></ul>")),
    ],
    qa=_qa(
        ("What belongs in a RAG golden set?", "question, gold_answer, gold_chunk_ids, optional difficulty/tags. 200–500 human-labeled pairs held out from tuning."),
        ("Key metrics for RAG?", "Retrieval: Recall@5, nDCG@5. Generation: faithfulness, answer relevance, context precision. Ops: p99 latency, cost/query."),
        ("LLM-as-judge reliability?", "Calibrate against human labels monthly. Use rubric + stronger judge model. Ensemble 3 judges for high-stakes."),
        ("When block a deploy?", "Faithfulness drop >5%, Recall@5 drop >2%, safety failure on red-team set, latency p99 regression >20%."),
        ("Synthetic eval bootstrap?", "LLM generates Q from docs; human verifies. Fast bootstrap but replace with human gold over time."),
        ("Eval agents vs RAG?", "Agents: task success rate, tool call accuracy, steps to completion, cost. Trajectory match against golden paths."),
        ("Ragas vs DeepEval?", "Both solid. Ragas RAG-focused metrics. DeepEval broader test cases. Pick one; integrate in CI."),
        ("How avoid eval leakage?", "Hold-out golden set never used in prompt tuning. Separate synthetic generation docs from eval docs."),
        ("Human eval cadence?", "Weekly 50-sample spot check. Full re-label quarterly. Inter-annotator agreement tracking."),
        ("Online vs offline eval?", "Offline golden set pre-deploy. Online A/B thumbs + implicit signals post-deploy. Both required."),
        ("Eval cost control?", "Smoke set 50 cases on every PR. Full 500-case nightly. Sample production 1% for continuous eval."),
        ("SDE3: build eval platform?", "Unified runner API, versioned golden sets, metric plugins, CI gate integration, human review UI, production feedback ingestion, per-team dashboards."),
    ),
)

# ── 8. production-agent ───────────────────────────────────────────────
TOPICS["production-agent"] = dict(
    title="Production Agent (HITL)",
    nav="Production Agent",
    hero="Ship agents safely: human-in-the-loop approvals, guardrails, tracing, cost caps, graceful degradation. Production agents are bounded loops, not autonomous AGI.",
    tags=_tags(("HITL", ""), ("Guardrails", " orange"), ("Tracing", " green"), ("Cost Cap", " pink"), ("Fallback", " blue")),
    main_img="production-agent-main.png",
    main_cap="Production agent stack: API gateway, agent orchestrator with termination controller, HITL approval queue, tool sandbox, guardrails filter, observability pipeline.",
    nav_items=_nav(("01","whatwhy","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),("02","whento","When to Use"),("03","architecture","Architecture"),("04","hitl","HITL"),("05","guardrails","Guardrails"),("06","tracing","Tracing"),("07","cost","Cost Caps"),("08","degrade","Graceful Degrade"),("09","production","Production & Ops"),("10","shows-up","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A")),
    sections=[
        ("whatwhy","01","What & Why", card("<p>Dev agents demo well; production agents fail on edge cases, cost overruns, and destructive actions. HITL and guardrails are non-negotiable for write actions.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),(("td","HITL"),("td","Human approves before risky action"),("td","Adds latency — async queue")),(("td","Guardrails"),("td","Input/output policy filters"),("td","Not a substitute for sandbox")),(("td","Circuit breaker"),("td","Stop calling failing tools"),("td","Need half-open retry")),]))),
        ("api","01b","API Surface", card('<pre>POST /v1/agent/run\n  { task, user_id, hitl_mode: "required_for_write" }\n  -> { run_id, status: "awaiting_approval", pending_action: {...} }\n\nPOST /v1/agent/runs/{id}/approve\n  -> resumes execution</pre>')),
        ("whento","02","When to Use / When NOT", card(tbl([(("th","Control"),("th","Use When"),("th","Skip When")),(("td","Full auto"),("td","Read-only search/RAG"),("td","Send email, charge card, delete data")),(("td","HITL"),("td","Write/destructive tools"),("td","Read-only always safe")),]))),
        ("architecture","03","Architecture", card('<pre>API GW -> Agent Orchestrator -> [Guardrails in/out] -> Tool Sandbox\n              |-> HITL Queue (async approve)\n              |-> Trace -> Langfuse/OTel</pre>')),
        ("hitl","04","Deep Dive: HITL", diag("production-agent","hitl-zoom","Agent pauses before send_email; human reviews in approval UI; approve or reject resumes or aborts") + card("<p>Classify tools: read (auto), write (approve), destructive (manager approve). Timeout 24h → abort with notification.</p>")),
        ("guardrails","05","Deep Dive: Guardrails", card("<p>Input: PII detection, prompt injection scan. Output: toxicity, data leak, off-topic. NeMo Guardrails, Guardrails AI, custom regex.</p>")),
        ("tracing","06","Deep Dive: Tracing", diag("production-agent","trace-zoom","OpenTelemetry trace showing LLM calls, tool executions, latencies, token counts per agent run") + card("<p>LangSmith, Langfuse, Arize. Span per LLM call and tool. Store prompts/responses for replay (PII redacted).</p>")),
        ("cost","07","Deep Dive: Cost Caps", card("<p>max_llm_calls=15, max_cost_usd=0.50 per run. Track token usage per span. Alert on 10× median cost queries.</p>")),
        ("degrade","08","Deep Dive: Graceful Degrade", card("<p>On timeout: return partial answer + 'could not complete action'. Fallback to simpler chain without tools. Never infinite spin.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Run replay suite on every deploy</li><li>On-call runbook for agent failures</li><li>Rate limit per user/org</li></ul>")),
        ("shows-up","10","Where It Shows Up", card('<ul><li><a href="agent-architectures.html">Agent Architectures</a></li><li><a href="multi-agent-orchestration.html">Multi-Agent</a></li><li><a href="tool-calling-functions.html">Tool Calling</a></li><li><a href="../tech/langgraph.html">LangGraph</a></li></ul>')),
        ("pitfalls","11","Common Pitfalls", card("<ul><li>No HITL on write tools</li><li>Logging full prompts with PII</li><li>No max_iterations — runaway loops</li><li>Guardrails only on output not input docs</li></ul>")),
    ],
    qa=_qa(
        ("When require HITL?", "Any write/destructive tool: email, ticket update, payment, delete. Read-only RAG can auto-run."),
        ("HITL sync vs async?", "Async default — user gets notification to approve. Sync only for live chat with operator present."),
        ("Guardrails vs sandbox?", "Guardrails filter content; sandbox restricts execution environment. Need both."),
        ("What trace for debugging?", "Every LLM call, tool name/args/latency, token counts, final outcome. Replay exact run from trace ID."),
        ("Cost cap implementation?", "Accumulate token cost per run_id. Hard stop when budget exceeded. Return partial result."),
        ("Graceful degradation patterns?", "Timeout → partial answer. Tool failure → tell user + suggest manual step. LLM down → cached FAQ."),
        ("LangGraph HITL?", "interrupt_before on write tool nodes. Checkpoint state. Resume after approve via API."),
        ("Red-team production agents?", "Prompt injection in retrieved docs. Tool argument injection. Privilege escalation across tenants."),
        ("SLA for agent tasks?", "Interactive: p95 <15s for read-only. Async write tasks: minutes with HITL queue."),
        ("Multi-tenant agent isolation?", "Separate tool creds per org. user_id/org_id in every tool call. No shared scratchpad."),
        ("Deploy checklist?", "Golden eval pass, HITL on write tools, max_iterations set, tracing on, cost cap, red-team spot check."),
        ("SDE3: production agent platform?", "Shared orchestrator, tool registry with ACL, HITL service, unified tracing, eval CI, per-team cost budgets, run replay debugger."),
    ),
)

# ── 9. semantic-cache ─────────────────────────────────────────────────
TOPICS["semantic-cache"] = dict(
    title="Semantic Cache",
    nav="Semantic Cache",
    hero="Cache LLM responses by embedding similarity, not exact string match. 40–60% hit rates on support bots — but wrong threshold causes confident wrong answers.",
    tags=_tags(("Embedding Cache", ""), ("Cosine Threshold", " orange"), ("TTL", " green"), ("Invalidation", " pink"), ("Cost Save", " blue")),
    main_img="semantic-cache-main.png",
    main_cap="Semantic cache flow: embed incoming query, ANN search cache index, if similarity > threshold return cached response else call LLM and store new entry.",
    nav_items=_nav(("01","whatwhy","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),("02","whento","When to Use"),("03","architecture","Architecture"),("04","threshold","Threshold Tuning"),("05","ttl","TTL & Freshness"),("06","invalidation","Invalidation"),("07","exact","Exact + Semantic"),("08","multitenant","Multi-Tenant"),("09","production","Production & Ops"),("10","shows-up","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A")),
    sections=[
        ("whatwhy","01","What & Why", card("<p>LLM inference is expensive. Many user queries are near-duplicates ('reset password' vs 'how do I reset my password'). Semantic cache cuts cost and latency.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),(("td","Cache hit"),("td","Similar query found above threshold"),("td","False hit = wrong answer confidently")),(("td","Threshold"),("td","Min cosine similarity for hit"),("td","0.92–0.97 depending on domain")),(("td","TTL"),("td","Time-to-live before cache miss forced"),("td","Stale policy answers")),]))),
        ("api","01b","API Surface", card('<pre>cache.lookup(query_embedding, org_id) -> { hit, response, score } | miss\ncache.store(query, embedding, response, ttl=3600, metadata={sources})\n\n# GPTCache / Redis + vector extension</pre>')),
        ("whento","02","When to Use / When NOT", card(tbl([(("th","Cache"),("th","Use When"),("th","Skip When")),(("td","Semantic"),("td","FAQ/support high repeat"),("td","Unique analytical queries")),(("td","Exact only"),("td","Deterministic API responses"),("td","Paraphrase-heavy support")),]))),
        ("architecture","03","Architecture", card('<pre>Query -> Embed -> Cache ANN lookup -> [hit: return] [miss: LLM -> store]</pre>')),
        ("threshold","04","Deep Dive: Threshold Tuning", diag("semantic-cache","threshold-zoom","ROC curve: false hit rate vs cache hit rate at thresholds 0.90, 0.93, 0.95, 0.97") + card("<p>Start 0.95. Lower = more hits + more false hits. Evaluate on query pairs labeled same/different intent.</p>")),
        ("ttl","05","Deep Dive: TTL & Freshness", card("<p>Policy docs: TTL 1–24h. Product FAQs: 7d. Include source content_hash in cache entry; invalidate on doc update.</p>")),
        ("invalidation","06","Deep Dive: Invalidation", diag("semantic-cache","invalidation-zoom","Doc update triggers purge of cache entries whose citations reference changed doc_id") + card("<p>On doc delete/update: purge entries with matching source doc_ids. Bloom filter for fast candidate check.</p>")),
        ("exact","07","Deep Dive: Exact + Semantic Two-Tier", card("<p>L1: exact hash match (Redis). L2: semantic ANN. Exact hits ~5ms; semantic ~15ms; both beat LLM ~800ms.</p>")),
        ("multitenant","08","Deep Dive: Multi-Tenant", card("<p>Namespace cache by org_id. Never return cache entry from different tenant even if similarity high.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Monitor hit rate, false hit rate (thumbs down on cached)</li><li>Cache stampede on cold start — pre-warm top queries</li></ul>")),
        ("shows-up","10","Where It Shows Up", card('<ul><li><a href="rag-end-to-end.html">RAG End-to-End</a></li><li><a href="chatbot-rag-system.html">Chatbot RAG System</a></li><li><a href="../fundamentals/embeddings-semantic-search.html">Embeddings</a></li><li><a href="../tech/vector-databases.html">Vector Databases</a></li></ul>')),
        ("pitfalls","11","Common Pitfalls", card("<ul><li>Threshold too low — wrong answers cached</li><li>No invalidation on doc update</li><li>Cross-tenant cache leakage</li><li>Caching personalized responses under shared key</li></ul>")),
    ],
    qa=_qa(
        ("Semantic vs exact cache?", "Exact: hash match only. Semantic: embedding similarity catches paraphrases. Use two-tier L1 exact + L2 semantic."),
        ("Typical hit rate?", "40–60% on support/FAQ bots. Near 0% on unique analytics. Measure before investing."),
        ("How pick threshold?", "Label 500 query pairs same/different intent. Plot hit rate vs false hit rate. Start 0.95 cosine."),
        ("Invalidate when docs change?", "Store source doc_ids in cache entry. On doc update/delete, purge matching entries. TTL as backstop."),
        ("Cache personalized answers?", "Include user_id or session context in cache key metadata. Don't return user-A answer to user-B."),
        ("GPTCache vs roll-your-own?", "GPTCache: plug-and-play. Roll-your-own Redis+pgvector if need tenant isolation and custom invalidation."),
        ("Latency savings?", "Cache hit ~15ms vs LLM ~800ms+. Massive p99 improvement for repeated intents."),
        ("False hit detection?", "Track thumbs-down on cached responses. Sample manual review. Auto-lower threshold region if false hits spike."),
        ("Cache LLM embeddings too?", "Yes — cache query embeddings separately (exact on embedding input) to skip embed API on repeat."),
        ("RAG + semantic cache?", "Cache final answer + citations. On hit, still verify source docs not updated since cached_at."),
        ("Cold start?", "Pre-warm from top 100 historical queries. Seed from FAQ canonical questions."),
        ("SDE3: semantic cache layer?", "Two-tier exact+semantic, org namespace, citation-aware invalidation, false-hit monitor, dashboard hit rate/latency/cost saved."),
    ),
)

# ── 10. document-ingestion ────────────────────────────────────────────
TOPICS["document-ingestion"] = dict(
    title="Document Ingestion Pipeline",
    nav="Doc Ingestion",
    hero="Parse, OCR, dedupe, chunk, embed, and index at scale. Ingest is 80% of RAG quality — garbage in, hallucination out.",
    tags=_tags(("Kafka", ""), ("OCR", " orange"), ("CDC", " green"), ("Dedup", " pink"), ("Near-line", " blue")),
    main_img="document-ingestion-main.png",
    main_cap="Document ingestion pipeline: sources (S3, Confluence, Slack) → Kafka queue → parser workers → dedup by content_hash → chunker → embed GPU pool → dual-write indexes + metadata DB.",
    nav_items=_nav(("01","whatwhy","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),("02","whento","When to Use"),("03","architecture","Architecture"),("04","parse","Parsing & OCR"),("05","dedup","Dedup & CDC"),("06","queue","Queue Design"),("07","embed","Embed Workers"),("08","freshness","Freshness"),("09","production","Production & Ops"),("10","shows-up","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A")),
    sections=[
        ("whatwhy","01","What & Why", card("<p>RAG quality ceiling is set at ingest. Parsing failures, bad OCR, and stale indexes cause retrieval misses before the query path runs.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),(("td","CDC"),("td","Change data capture from sources"),("td","Miss deletes without webhooks")),(("td","content_hash"),("td","SHA256 of normalized text"),("td","Skip re-embed if unchanged")),(("td","Near-line"),("td","Minutes freshness via streaming ingest"),("td","Higher cost than batch")),]))),
        ("api","01b","API Surface", card('<pre>POST /v1/documents { source_url, org_id, metadata }\n  -> 202 { job_id, status: "QUEUED" }\nGET  /v1/documents/{doc_id} -> { status, chunk_count, content_hash }\nDELETE /v1/documents/{doc_id} -> 204 tombstone</pre>')),
        ("whento","02","When to Use / When NOT", card(tbl([(("th","Mode"),("th","Use When"),("th","Skip When")),(("td","Batch nightly"),("td","Stable docs, cost-sensitive"),("td","Need minute freshness")),(("td","Near-line CDC"),("td","Confluence/Notion live sync"),("td","Static PDF archive")),]))),
        ("architecture","03","Architecture", card('<pre>Sources -> Kafka -> Parser -> Dedup -> Chunker -> Embed -> [Vector + Sparse + Postgres meta]</pre>')),
        ("parse","04","Deep Dive: Parsing & OCR", diag("document-ingestion","parse-zoom","Parser routing: PDF to OCR/unstructured, HTML to trafilatura, Slack JSON to thread builder") + card("<p>Unstructured, Docling, Tesseract OCR. Preserve tables. Strip boilerplate nav/footer.</p>")),
        ("dedup","05","Deep Dive: Dedup & CDC", card("<p>content_hash skip if unchanged. CDC webhooks from Confluence/ Drive. Tombstone on delete; async index purge.</p>")),
        ("queue","06","Deep Dive: Queue Design", diag("document-ingestion","queue-zoom","Kafka partitioned by org_id; consumer groups for parser, chunker, embed stages with DLQ") + card("<p>Kafka/SQS with DLQ. Backpressure when embed GPU saturated. Priority queue for user-triggered refresh.</p>")),
        ("embed","07","Deep Dive: Embed Workers", card("<p>GPU pool batching 256 chunks/call. Idempotent upsert by chunk_id. Rate limit per org.</p>")),
        ("freshness","08","Deep Dive: Freshness", card("<p>Target: new doc searchable &lt;5 min. Monitor ingest lag p99. Reconciliation job nightly for missed CDC events.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Parser failure rate by mime type dashboard</li><li>DLQ replay tooling</li><li>Ingest lag alerts</li></ul>")),
        ("shows-up","10","Where It Shows Up", card('<ul><li><a href="rag-end-to-end.html">RAG End-to-End</a></li><li><a href="chunking-strategies.html">Chunking Strategies</a></li><li><a href="hybrid-search.html">Hybrid Search</a></li><li><a href="../../hld/job-scheduler.html">Job Scheduler HLD</a></li></ul>')),
        ("pitfalls","11","Common Pitfalls", card("<ul><li>Sync ingest blocking API</li><li>No tombstone on delete — zombie chunks</li><li>OCR quality ignored</li><li>Re-embed entire corpus on 1% change</li></ul>")),
    ],
    qa=_qa(
        ("Sync vs async ingest?", "Always async. POST returns 202 job_id. User queries poll or webhook. Never block on embedding 1M docs."),
        ("How handle doc deletes?", "Tombstone in metadata DB. Async purge vector+sparse by doc_id. Verify purge in reconciliation job."),
        ("content_hash purpose?", "Skip re-chunk/re-embed if document unchanged. Saves GPU on CDC noise."),
        ("Parser selection?", "Route by mime: PDF→Unstructured/OCR, HTML→trafilatura, markdown→direct, Slack→custom thread parser."),
        ("Kafka vs SQS?", "Kafka for high-throughput ordered CDC streams. SQS simpler for moderate scale job queue."),
        ("Ingest lag SLA?", "Near-line: p99 <5 min. Batch: <24h. Alert when lag exceeds 2× baseline."),
        ("OCR quality?", "Sample 1% human review. Confidence threshold; flag low-confidence pages for manual review."),
        ("Multi-tenant ingest?", "Partition queue by org_id. Fair scheduling — prevent one tenant saturating embed pool."),
        ("Re-embed on model upgrade?", "Blue/green index: embed to new index version, swap alias after golden eval. Don't delete old until validated."),
        ("DLQ handling?", "Parser failures → DLQ with raw doc. Replay after fix. Alert on DLQ depth."),
        ("Ingest 1M docs sizing?", "10M chunks. Embed ~3 GPU-hours one-time. Kafka 3-node. Parser CPU fleet auto-scaled."),
        ("SDE3: ingestion platform?", "Pluggable parsers, CDC connectors, content_hash dedup, priority queues, embed GPU autoscaler, quality dashboard, GDPR delete pipeline."),
    ),
)

# ── 11. chatbot-rag-system (HLD depth) ────────────────────────────────
TOPICS["chatbot-rag-system"] = dict(
    title="Chatbot with RAG (System Design)",
    nav="Chatbot RAG",
    hero="Full system design: enterprise chatbot with RAG, conversation memory, semantic cache, agent tools, and HITL. The canonical 45-minute AI system design interview.",
    tags=_tags(("System Design", ""), ("10K QPS", " orange"), ("Multi-tenant", " green"), ("Streaming", " pink"), ("HITL", " blue")),
    main_img="chatbot-rag-system-main.png",
    main_cap="Chatbot RAG system HLD: client apps → API gateway → chat service (session, memory, cache) → RAG pipeline → optional agent tools → LLM fleet with streaming SSE responses.",
    nav_items=_nav(("01","whatwhy","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API & Entities"),("02","whento","When to Use"),("03","architecture","Architecture"),("03a","estimation","Estimation"),("04","entities","Core Entities"),("05","chatpath","Chat Path"),("06","ragpath","RAG Integration"),("07","memory","Session Memory"),("08","agents","Agent Tools"),("09","production","Production & Ops"),("10","shows-up","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A")),
    sections=[
        ("whatwhy","01","What & Why", card("<h3>Functional Requirements</h3><ul><li>Multi-turn chat with conversation history</li><li>Answer from private enterprise knowledge base with citations</li><li>Execute actions (create ticket, search CRM) via agent tools</li><li>Stream responses token-by-token</li><li>Admin: ingest docs, view analytics, configure bot persona</li></ul><h3>Non-Functional Requirements</h3><ul><li>10K QPS peak; p99 first token &lt;500ms</li><li>Multi-tenant isolation (org_id, ACL)</li><li>99.9% availability</li><li>GDPR: delete user data within 30 days</li><li>Cost budget: &lt;$0.05 per query average</li></ul>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),(("td","Session"),("td","Conversation thread with message history"),("td","Unbounded history exceeds context")),(("td","Router"),("td","Classifies simple FAQ vs RAG vs agent path"),("td","Wrong route wastes cost or misses tools")),(("td","Grounding"),("td","Answer constrained to retrieved docs"),("td","Need eval not just prompt")),]))),
        ("api","01b","API & Entities", card('<pre>POST /v1/chat/sessions { org_id, user_id } -> { session_id }\nPOST /v1/chat/sessions/{id}/messages\n  { content, stream: true } -> SSE tokens + citations event\n\nGET  /v1/chat/sessions/{id}/messages -> history\nPOST /v1/documents (ingest) -> 202 job_id\n\nEntities: Organization, User, Session, Message, Document, Chunk,\n         Citation, ToolRun, CacheEntry, Feedback</pre>')),
        ("whento","02","When to Use / When NOT", card(tbl([(("th","Component"),("th","Include When"),("th","Defer When")),(("td","RAG"),("td","Private knowledge required"),("td","General chit-chat only")),(("td","Agent tools"),("td","User expects actions"),("td","Read-only FAQ")),(("td","Semantic cache"),("td","High repeat query rate"),("td","Unique queries every time")),]))),
        ("architecture","03","Architecture", card('<pre>Clients -> CDN/API GW -> Chat Service\n  -> Query Router -> [Cache hit] | [RAG path] | [Agent path]\n  RAG: embed -> hybrid retrieve -> rerank -> LLM stream\n  Agent: tool loop with HITL on writes\n  Session store (Redis) + Memory (vector) + Postgres metadata</pre>') + diag("chatbot-rag-system","architecture-zoom","Detailed chat service components: router, session store, RAG retriever, LLM gateway, streaming SSE")),
        ("estimation","03a","Estimation (1M docs, 10K QPS)", card('<pre>Corpus: 1M docs -> ~10M chunks\nStorage: ~120GB vectors + 30GB sparse + 5GB metadata\n10K QPS: semantic cache 40% hit -> 6K to LLM\nLLM fleet: vLLM ~200 GPUs or tiered model routing\nRAG retrieve: 50 ANN shards, rerank bottleneck -> top-20\nCost: cache saves ~40% LLM spend; avg $0.03/query achievable</pre>')),
        ("entities","04","Core Entities", diag("chatbot-rag-system","entities-zoom","ER diagram: Organization, User, Session, Message, Document, Chunk, Citation, ToolRun relationships") + card("<p><strong>Session</strong> owns Messages. <strong>Message</strong> has role, content, citations[], tool_runs[]. <strong>Document</strong> 1:N Chunks. <strong>Citation</strong> links Message to Chunk with snippet.</p>")),
        ("chatpath","05","Deep Dive: Chat Path", card("<ol><li>Auth + rate limit</li><li>Load session history; summarize if >8K tokens</li><li>Semantic cache lookup</li><li>Router: FAQ / RAG / agent</li><li>Stream LLM response via SSE</li><li>Persist message + citations; async feedback</li></ol>")),
        ("ragpath","06","Deep Dive: RAG Integration", card("<p>See <a href='rag-end-to-end.html'>RAG End-to-End</a>. Hybrid retrieve top-50, rerank top-5, inject numbered passages, generate with [1][2] citations. Refuse if max rerank score below threshold.</p>")),
        ("memory","07","Deep Dive: Session Memory", card("<p>Redis session buffer. Rolling summary over 8K tokens. Long-term vector memory for user prefs (<a href='agent-memory.html'>Agent Memory</a>).</p>")),
        ("agents","08","Deep Dive: Agent Tools", card("<p>Optional agent path for ticket creation, CRM lookup. HITL on writes (<a href='production-agent.html'>Production Agent</a>). Max 8 tool calls.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Eval harness CI gate on every deploy</li><li>Tracing: cache/RAG/agent/LLM spans</li><li>Moderation on input and output</li><li>Per-org usage billing dashboard</li></ul>")),
        ("shows-up","10","Where It Shows Up", card('<ul><li><a href="rag-end-to-end.html">RAG End-to-End</a></li><li><a href="semantic-cache.html">Semantic Cache</a></li><li><a href="production-agent.html">Production Agent</a></li><li><a href="../../hld/web-search-engine.html">Web Search Engine HLD</a></li></ul>')),
        ("pitfalls","11","Common Pitfalls", card("<ul><li>No query router — every query hits expensive RAG</li><li>Session history unbounded</li><li>Missing citation verification</li><li>No tenant isolation on cache and retrieval</li></ul>")),
    ],
    qa=_qa(
        ("Design a chatbot with RAG from scratch.", "Clarify: corpus size, QPS, multi-tenant, actions needed. Draw: API GW → Chat Service → Router → Cache/RAG/Agent paths. Offline ingest pipeline. Session in Redis. Stream via SSE. Citations required."),
        ("Core entities?", "Organization, User, Session, Message, Document, Chunk, Citation, ToolRun, Feedback. Session 1:N Messages. Document 1:N Chunks."),
        ("API design?", "POST sessions, POST messages with stream:true → SSE, async ingest POST /documents. Idempotent message IDs for retry."),
        ("Size for 1M docs, 10K QPS?", "10M chunks, 120GB vectors. Cache 40% hits. 6K QPS LLM — tiered models + vLLM fleet. Rerank bottleneck — reduce to top-20."),
        ("Router purpose?", "Classify simple FAQ (cached/template), RAG-needed (knowledge), agent-needed (action). Saves cost and latency."),
        ("Multi-tenant isolation?", "org_id on every query, cache namespace, vector pre-filter. Separate encryption keys per enterprise tier."),
        ("Streaming implementation?", "SSE from LLM token stream. Send citations in final event. Client renders incrementally."),
        ("When add agent tools?", "When users need actions beyond Q&A. HITL on writes. Cap tool calls. Fallback to RAG-only if tools fail."),
        ("Memory architecture?", "Short: session buffer in Redis. Long: vector memory for prefs. Summarize when >8K tokens."),
        ("Eval strategy?", "Golden 500 Q&A. Faithfulness + Recall@5 CI gate. Online thumbs feedback. Weekly human spot check."),
        ("Cost optimization?", "Semantic cache, query router, smaller model for easy queries, rerank top-20, batch embed ingest."),
        ("SDE3: 12-month evolution?", "M1–3: RAG baseline + eval. M4–6: cache + router + memory. M7–9: agent tools + HITL. M10–12: fine-tuned reranker, multi-region, 50% cost reduction."),
    ),
)
