# ai_tech_content_p3.py — topics 7–12

# ── 7. pgvector ─────────────────────────────────────────────────────
TOPICS["pgvector"] = dict(
    title="pgvector",
    nav="pgvector",
    hero="PostgreSQL extension for vector similarity search: store embeddings alongside relational data, HNSW/IVFFlat indexes, SQL WHERE filters, and ACID transactions — the default when you already run Postgres.",
    tags=_tags(("Postgres", ""), ("HNSW", " orange"), ("SQL", " green"), ("ACID", " pink"), ("JOIN", " purple")),
    main_img="pgvector-main.png",
    main_cap="pgvector in Postgres: embeddings column type vector(1536), HNSW index, SQL WHERE tenant filter, JOIN with users/orders in one query. Sweet spot: 100K–10M vectors per instance.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","hnsw","HNSW Index"),
        ("05","sql","SQL Patterns"),("06","ivf","IVFFlat"),("07","hybrid","Hybrid with FTS"),
        ("08","compare","vs Others"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p><strong>pgvector</strong> adds <code>vector</code> type and distance operators to Postgres. One database for users, documents, embeddings, and ACL joins — no separate vector SaaS. See <a href=\"vector-databases.html\">Vector DB overview</a>.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","vector(n)"),("td","Fixed-dimension float column"),("td","n must match embed model")),
            (("td","<=>"),("td","Cosine distance operator"),("td","Use vector_cosine_ops index")),
            (("td","HNSW"),("td","Graph ANN index (PG 16+)"),("td","RAM hungry; tune m, ef_construction")),
            (("td","IVFFlat"),("td","Cluster-based ANN"),("td","Needs ANALYZE after build")),
        ]))),
        ("api","01b","API Surface", card('<pre>CREATE EXTENSION vector;\n\nCREATE TABLE chunks (\n  id BIGSERIAL PRIMARY KEY,\n  tenant_id TEXT NOT NULL,\n  content TEXT,\n  embedding vector(1536),\n  metadata JSONB\n);\n\nCREATE INDEX ON chunks\n  USING hnsw (embedding vector_cosine_ops)\n  WITH (m = 16, ef_construction = 128);\n\nSET hnsw.ef_search = 100;\n\nSELECT id, content, embedding <=> $1 AS dist\nFROM chunks\nWHERE tenant_id = $2\nORDER BY embedding <=> $1\nLIMIT 20;</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Case"),("th","pgvector?"),("th","Alt")),
            (("td","On Postgres, &lt;10M vec"),("td","Yes"),("td","Pinecone")),
            (("td","Need JOIN with SQL"),("td","Yes"),("td","Sync to vector DB")),
            (("td","100M+ vectors"),("td","Maybe shard"),("td","Dedicated vector store")),
        ]))),
        ("architecture","03","Architecture", card("<p>App → Postgres (pgvector + relational tables) → optional read replica for search QPS. Ingest via COPY/batch INSERT; async index build CONCURRENTLY.</p>")),
        ("hnsw","04","Deep Dive: HNSW", diag("pgvector","hnsw-zoom","HNSW index params m=16 ef_construction=128; query SET hnsw.ef_search=100 for recall/latency tradeoff") + card("<p>Increase ef_search when recall@k drops on eval. Monitor index size vs shared_buffers.</p>")),
        ("sql","05","Deep Dive: SQL Patterns", diag("pgvector","sql-zoom","SQL query: WHERE tenant_id + ORDER BY embedding <=> query_vec LIMIT 20 with JOIN to documents table") + card("<p>Combine ACL: JOIN user_doc_access ON doc_id. Transactional upsert with ON CONFLICT.</p>")),
        ("ivf","06","IVFFlat", card("<p>CREATE INDEX USING ivfflat WITH (lists = 100); SET ivfflat.probes = 10; cheaper RAM than HNSW for large N if recall tuned.</p>")),
        ("hybrid","07","Hybrid with FTS", card("<p>Postgres tsvector + pgvector: dual query in SQL or app; RRF merge. ParadeDB extension for better BM25. <a href=\"../systems/hybrid-search.html\">Hybrid Search</a>.</p>")),
        ("compare","08","vs Others", card("<p>vs <a href=\"pinecone.html\">Pinecone</a>: pgvector = SQL + lower cost at moderate scale; Pinecone = zero ops at huge scale.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Connection pool (PgBouncer); read replicas for search</li><li>VACUUM after bulk delete; REINDEX on model change</li><li>Partition large tables by tenant_id</li></ul>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="vector-databases.html">Vector Databases</a></li><li><a href="../systems/rag-end-to-end.html">RAG End-to-End</a></li><li><a href="chroma.html">Chroma</a> (dev alternative)</li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>Wrong ops class (L2 vs cosine)</li><li>No index — seq scan timeout</li><li>ef_search too low — bad recall</li><li>Storing huge content in vector table — use pointer</li></ul>")),
    ],
    qa=_qa(
        ("Why pgvector?", "Single Postgres for relational + vector + ACID. JOIN embeddings with permissions. Team already knows SQL ops."),
        ("HNSW vs IVFFlat in pgvector?", "HNSW default for recall/latency. IVFFlat when RAM constrained and N large — tune lists/probes."),
        ("How filter by tenant?", "WHERE tenant_id = $1 before ORDER BY distance — uses B-tree on tenant_id + HNSW together."),
        ("ef_search tuning?", "Start 40–100; increase until recall@10 on golden set ≥0.92; watch p99 latency."),
        ("Max vectors per instance?", "Roughly 1–10M with HNSW on 1536-dim depending on RAM. Beyond: read replicas, partitioning, or dedicated vector DB."),
        ("Embedding dimension mismatch?", "CREATE TABLE fails or query errors. Alter column or new table on model change."),
        ("Hybrid search?", "ts_rank + vector distance in app layer RRF; or ParadeDB for unified query."),
        ("Migrations?", "Enable extension; add column; backfill embed; CREATE INDEX CONCURRENTLY; swap read traffic."),
        ("pgvector vs Pinecone cost?", "pgvector = Postgres you already pay. Pinecone = per read/storage — cheaper ops time, higher $ at hyperscale."),
        ("Backup?", "Standard Postgres pg_dump/WAL; vectors included like any column."),
        ("Concurrent upsert?", "ON CONFLICT (id) DO UPDATE; batch transactions; avoid index bloat with autovacuum tuning."),
        ("SDE3: pgvector RAG for 5M chunks?", "Partition by tenant; HNSW per partition or shared with tenant_id index; read replicas; ingest worker pool; hybrid FTS column; reranker service; golden eval weekly."),
    ),
)

# ── 8. chroma ───────────────────────────────────────────────────────
TOPICS["chroma"] = dict(
    title="Chroma",
    nav="Chroma",
    hero="Embedded open-source vector database for local dev and prototypes: pip install, in-process or client/server mode, collections, metadata filters, and LangChain/LlamaIndex integration.",
    tags=_tags(("Embedded", ""), ("Collections", " orange"), ("Dev", " green"), ("LangChain", " pink"), ("Local", " purple")),
    main_img="chroma-main.png",
    main_cap="Chroma: Python client → Collection (embed + metadata + ids) → HNSW in-process or Chroma server → query top-k. Ideal for notebooks and CI; graduate before production SLAs.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","collections","Collections"),
        ("05","embed","Embedding Functions"),("06","client","Client/Server"),("07","integrate","Integrations"),
        ("08","graduation","Graduation Path"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p><strong>Chroma</strong> is the fastest path to a working vector store in Python. Zero infra for demos and tests. Not a substitute for <a href=\"pinecone.html\">Pinecone</a> or <a href=\"pgvector.html\">pgvector</a> at multi-tenant production scale.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","Collection"),("td","Named set of embeddings + docs"),("td","Like Pinecone namespace")),
            (("td","PersistentClient"),("td","Disk-backed storage"),("td","Path survives restarts")),
            (("td","EmbeddingFunction"),("td","Auto-embed on add/query"),("td","Must match prod model")),
        ]))),
        ("api","01b","API Surface", card('<pre>import chromadb\nfrom chromadb.utils import embedding_functions\n\nef = embedding_functions.OpenAIEmbeddingFunction(\n    api_key="...", model_name="text-embedding-3-small")\nclient = chromadb.PersistentClient(path="./chroma_db")\ncol = client.get_or_create_collection("docs", embedding_function=ef)\n\ncol.add(ids=["1"], documents=["Refund within 30 days"], metadatas=[{"type": "policy"}])\nresults = col.query(query_texts=["return policy"], n_results=5)</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Case"),("th","Chroma?"),("th","Alt")),
            (("td","Notebook RAG demo"),("td","Yes"),("td","—")),
            (("td","CI unit tests"),("td","Yes"),("td","In-memory fake")),
            (("td","Production multi-tenant"),("td","No"),("td","Pinecone/pgvector")),
        ]))),
        ("architecture","03","Architecture", card("<p>In-process SQLite + HNSW for PersistentClient; optional Docker server for team sharing.</p>")),
        ("collections","04","Deep Dive: Collections", diag("chroma","collections-zoom","Collection schema: ids, embeddings, documents, metadatas; query with where filter") + card("<p>where={\"type\": \"policy\"} metadata filter. update/delete by id.</p>")),
        ("embed","05","Embedding Functions", diag("chroma","embed-zoom","Embedding function pipeline: document text → OpenAI embed → store vector on add and query") + card("<p>Bring your own vectors with add(embeddings=...) for prod model parity testing.</p>")),
        ("client","06","Client/Server", card("<p>HttpClient to chroma run --host — shared dev server. Not HA production cluster.</p>")),
        ("integrate","07","Integrations", card("<p>LangChain Chroma vectorstore; LlamaIndex ChromaVectorStore. Swap to Pinecone with same chunk pipeline.</p>")),
        ("graduation","08","Graduation Path", card("<p>Prototype Chroma → swap VectorStore backend to pgvector/Pinecone; keep same chunk IDs and metadata schema.</p>")),
        ("production","09","Production & Ops", card("<p>Chroma not recommended for prod SLAs. If forced: persistent volume, single-tenant, backup collection dir.</p>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="vector-databases.html">Vector Databases</a></li><li><a href="langchain.html">LangChain</a></li><li><a href="llamaindex.html">LlamaIndex</a></li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>Chroma in prod with paying users</li><li>Default embed model ≠ prod model</li><li>No tenant isolation in shared server</li></ul>")),
    ],
    qa=_qa(
        ("What is Chroma best for?", "Local dev, notebooks, CI tests, hackathons — vector search in 5 lines without cloud signup."),
        ("Persistent vs in-memory?", "PersistentClient saves to disk; EphemeralClient for tests. In-memory lost on exit."),
        ("How filter metadata?", "query(where={\"field\": \"value\"}) or where_document for text contains."),
        ("Chroma vs FAISS?", "Chroma: metadata, persistence, API. FAISS: raw index library — faster but DIY everything."),
        ("Production ready?", "Generally no for multi-tenant SaaS — no managed HA, limited scale. Use pgvector/Pinecone."),
        ("Embedding function gotcha?", "Chroma can embed for you — ensure same model as production pipeline."),
        ("LangChain integration?", "from langchain_chroma import Chroma — drop-in with retriever pattern."),
        ("Migrate to Pinecone?", "Export ids, embeddings, metadata; upsert to Pinecone namespace; switch retriever config."),
        ("Client/server mode?", "Docker chroma for team; still not production cluster replacement."),
        ("Collection sizing?", "Fine to ~500K vectors local; slows beyond — signals graduation time."),
        ("Backup?", "Copy persist directory; no built-in replication."),
        ("SDE3: when allow Chroma?", "Only dev/staging with synthetic data; contract test that retriever interface swaps to pgvector in prod config."),
    ),
)

# ── 9. embedding-models ─────────────────────────────────────────────
TOPICS["embedding-models"] = dict(
    title="Embedding Models",
    nav="Embeddings",
    hero="Choose and deploy text embedding models: OpenAI text-embedding-3, Cohere embed-v3, open-source BGE/E5, Matryoshka dimensions, cosine metrics, and eval before you pick an index.",
    tags=_tags(("text-embedding-3", ""), ("BGE", " orange"), ("Cosine", " green"), ("Matryoshka", " pink"), ("MTEB", " purple")),
    main_img="embedding-models-main.png",
    main_cap="Embedding model selection: text → tokenizer → encoder → L2-normalized vector (384–3072 dim) → cosine similarity in vector DB. Match model at ingest and query; version in index namespace.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","models","Model Comparison"),
        ("05","metric","Distance Metric"),("06","matryoshka","Matryoshka"),
        ("07","opensource","Open Source"),("08","eval","Eval"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p>Retrieval quality ceiling is set by <strong>embedding model</strong> before chunking tuning or rerankers. Wrong model or metric wastes index work. Primer: <a href=\"../fundamentals/embeddings-semantic-search.html\">Embeddings &amp; Semantic Search</a>.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","Bi-encoder"),("td","Single forward pass for query and doc"),("td","Fast retrieval; not reranker")),
            (("td","MTEB"),("td","Benchmark leaderboard for embed models"),("td","Your domain may differ")),
            (("td","Matryoshka"),("td","Truncate dims with less quality loss"),("td","OpenAI v3 supports dimensions param")),
            (("td","Normalization"),("td","L2 unit vectors"),("td","Dot product = cosine when normalized")),
        ]))),
        ("api","01b","API Surface", card('<pre># OpenAI\nclient.embeddings.create(model="text-embedding-3-small", input=texts, dimensions=512)\n\n# Cohere\nco.embed(texts=texts, model="embed-english-v3.0", input_type="search_document")\n\n# Local sentence-transformers\nfrom sentence_transformers import SentenceTransformer\nmodel = SentenceTransformer("BAAI/bge-small-en-v1.5")\nvecs = model.encode(texts, normalize_embeddings=True)</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Model"),("th","When"),("th","Skip")),
            (("td","text-embedding-3-small"),("td","Default SaaS RAG"),("td","Air-gapped")),
            (("td","bge-large"),("td","Self-host, no API cost"),("td","No GPU ops team")),
            (("td","embed-v3 multilingual"),("td","50+ languages"),("td","English-only corpus")),
        ]))),
        ("architecture","03","Architecture", card("<p>Embed service (API or GPU worker) → batch queue → vector DB. Cache query embeddings 5–60 min TTL for hot questions.</p>")),
        ("models","04","Deep Dive: Model Comparison", diag("embedding-models","models-zoom","Comparison table: OpenAI 3-small, Cohere v3, bge-small — dims, cost, MTEB score, latency") + card(tbl([(("th","Model"),("th","Dim"),("th","Notes")),
            (("td","text-embedding-3-small"),("td","1536 (512 trunc)"),("td","Best $/quality hosted")),
            (("td","text-embedding-3-large"),("td","3072"),("td","Higher recall, 2× cost")),
            (("td","embed-english-v3"),("td","1024"),("td","input_type search_query vs document")),
            (("td","bge-small-en"),("td","384"),("td","Fast local CPU/GPU")),
        ]))),
        ("metric","05","Distance Metric", diag("embedding-models","metric-zoom","Cosine vs L2 vs dot product: normalized vectors make dot equal cosine; pick ops class to match") + card("<p>OpenAI: cosine. BGE: normalize + inner product. pgvector: vector_cosine_ops.</p>")),
        ("matryoshka","06","Matryoshka", card("<p>text-embedding-3 dimensions=512 saves storage with ~2% recall loss on many tasks — validate on golden set.</p>")),
        ("opensource","07","Open Source", card("<p>BGE, E5, GTE on HuggingFace + sentence-transformers. vLLM/tei for batch GPU serving. <a href=\"model-serving-vllm.html\">Model Serving</a>.</p>")),
        ("eval","08","Eval", card("<p>Golden queries → recall@k vs labels. Compare models before re-index commitment. nDCG on ranked lists.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Version tag embed_model in metadata</li><li>Batch size 64–256 for GPU</li><li>Rate limit OpenAI embed API</li></ul>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="vector-databases.html">Vector Databases</a></li><li><a href="openai-api-patterns.html">OpenAI API Patterns</a></li><li><a href="rerankers.html">Rerankers</a></li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>Query/doc input_type mismatch (Cohere)</li><li>Not normalizing open-source vectors</li><li>Re-ranking without fixing embed first</li></ul>")),
    ],
    qa=_qa(
        ("How pick embedding model?", "Start text-embedding-3-small or bge-small; eval recall@5 on golden set; upgrade if &lt; target; consider cost and self-host constraints."),
        ("OpenAI small vs large?", "Large ~+3–5% recall on hard sets, 2× cost and storage. A/B on your data before defaulting to large."),
        ("What is Matryoshka?", "Embeddings trained so first k dimensions still useful — truncate 1536→512 for cheaper index with small recall trade."),
        ("Cosine vs dot product?", "For normalized vectors, equivalent. Use index ops matching your normalization pipeline."),
        ("Cohere input_type?", "search_document at ingest, search_query at query time — asymmetric embed improves retrieval."),
        ("Open source when?", "Air-gap, cost at billions of tokens, fine-tune on domain. Pay GPU ops."),
        ("Fine-tune embeddings?", "Rare; only with large labeled query-doc pairs. LoRA on encoder; re-eval vs bigger off-shelf."),
        ("Multilingual?", "embed-multilingual-v3 or multilingual-e5-large; eval per language slice."),
        ("Embed long documents?", "Chunk first — embed models have 512–8192 token limits. Never embed 100-page PDF whole."),
        ("Cache embeddings?", "Cache query vectors by hash(question); invalidate on model change."),
        ("MTEB trust?", "Starting point only — always domain golden set. Legal/medical need specialty eval."),
        ("SDE3: embed platform for company?", "Central embed API; model registry; batch GPU workers; versioned namespaces; automatic re-index job on model bump; cost allocation per team."),
    ),
)

# ── 10. rerankers ───────────────────────────────────────────────────
TOPICS["rerankers"] = dict(
    title="Rerankers",
    nav="Rerankers",
    hero="Two-stage retrieval: bi-encoder pulls top-50 fast, cross-encoder reranker scores query-passage pairs precisely → top-5 to LLM. The standard precision boost after vector DB.",
    tags=_tags(("Cross-Encoder", ""), ("Two-Stage", " orange"), ("Cohere", " green"), ("bge-reranker", " pink"), ("Latency", " purple")),
    main_img="rerankers-main.png",
    main_cap="Two-stage pipeline: vector DB top_k=50 (~20ms) → cross-encoder rerank (~50–80ms for 50 pairs) → top 5 chunks to LLM. Typical +15–25% nDCG vs bi-encoder alone.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","cross","Cross-Encoder"),
        ("05","models","Models"),("06","pipeline","Pipeline Tuning"),("07","latency","Latency"),
        ("08","compare","Hosted vs Local"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p>Bi-encoders embed query and doc separately — fast but shallow similarity. <strong>Cross-encoders</strong> joint-attend query+passage — slow but accurate. Always rerank after ANN in production RAG when latency budget allows ~50–100 ms.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","Bi-encoder"),("td","Separate embeddings, cosine search"),("td","Retrieval stage")),
            (("td","Cross-encoder"),("td","Single model on [query, passage]"),("td","O(pairs) — cap candidates")),
            (("td","top_k retrieve"),("td","ANN candidates before rerank"),("td","20–50 typical")),
            (("td","top_n output"),("td","Chunks to LLM after rerank"),("td","3–8 typical")),
        ]))),
        ("api","01b","API Surface", card('<pre># Cohere Rerank\nco.rerank(model="rerank-english-v3.0", query=q, documents=passages, top_n=5)\n\n# sentence-transformers CrossEncoder\nfrom sentence_transformers import CrossEncoder\nce = CrossEncoder("BAAI/bge-reranker-v2-m3")\nscores = ce.predict([[q, p] for p in passages])\ntop = sorted(zip(passages, scores), key=lambda x: -x[1])[:5]</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Case"),("th","Rerank?"),("th","Skip")),
            (("td","Production RAG Q&A"),("td","Yes"),("td","—")),
            (("td","Sub-100ms hard SLA"),("td","Maybe lite"),("td","Bi-encoder only")),
            (("td","Tiny corpus &lt;500 docs"),("td","Optional"),("td","Full cross-encoder scan OK")),
        ]))),
        ("architecture","03","Architecture", card('<pre>Query -> Embed -> Vector DB (k=50) -> Reranker (n=5) -> Prompt -> LLM</pre>')),
        ("cross","04","Deep Dive: Cross-Encoder", diag("rerankers","crossencoder-zoom","Cross-encoder joint attention on query+passage pair; scores relevance 0-1") + card("<p>Cannot pre-compute doc side — must run per query-passage pair at query time.</p>")),
        ("models","05","Models", diag("rerankers","pipeline-zoom","Pipeline: bi-encoder k=50, Cohere rerank top_n=5, latency budget 120ms total retrieve stage") + card("<p>Cohere rerank-english-v3.0, bge-reranker-v2-m3, ms-marco-MiniLM — pick by language and latency.</p>")),
        ("pipeline","06","Pipeline Tuning", card("<p>Sweep retrieve_k ∈ {20,50,100} and rerank_n ∈ {3,5,8} on golden nDCG. Diminishing returns above k=50 for most corpora.</p>")),
        ("latency","07","Latency", card("<p>50 passages × cross-encoder ~50–80 ms GPU; batch pairs. Cohere API ~100–200 ms. Budget total retrieve+rerank &lt;150 ms p99.</p>")),
        ("compare","08","Hosted vs Local", card("<p>Cohere: zero ops. Local GPU: lower $ at high QPS. CPU MiniLM for dev only.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Log rerank scores for drift detection</li><li>Fallback to ANN order if reranker timeout</li><li>A/B rerank on/off for quality metrics</li></ul>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="vector-databases.html">Vector Databases</a></li><li><a href="../systems/rag-end-to-end.html">RAG End-to-End</a></li><li><a href="../systems/hybrid-search.html">Hybrid Search</a></li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>rerank 200 passages — timeout</li><li>Skip rerank with hybrid already — still helps precision</li><li>Wrong language model for multilingual</li></ul>")),
    ],
    qa=_qa(
        ("Bi-encoder vs cross-encoder?", "Bi-encoder: embed separately, fast ANN. Cross-encoder: joint model on pair, accurate slow. Retrieve with bi-encoder, rerank with cross-encoder."),
        ("Why not only cross-encoder?", "Can't pre-index passages — linear scan over corpus too slow. Two-stage is industry standard."),
        ("How many candidates to rerank?", "Start 50 → rerank to 5. Increase k if recall@50 low on eval; decrease if latency high."),
        ("Cohere vs bge-reranker?", "Cohere hosted easy. bge self-host on GPU for cost at scale and air-gap."),
        ("Latency budget?", "Target retrieve+rerank &lt;150 ms p99. Batch cross-encoder pairs; GPU inference server."),
        ("Rerank after hybrid?", "Yes — hybrid improves recall; rerank improves precision on fused list."),
        ("Score threshold?", "Drop passages below score 0.3 — reduces hallucination from irrelevant chunks."),
        ("Multilingual rerank?", "bge-reranker-v2-m3 or Cohere multilingual — match query language."),
        ("Fine-tune reranker?", "With click/logs pairs — smaller lift than fixing chunking/embed; advanced optimization."),
        ("Failure fallback?", "On reranker timeout return ANN top-5 — degrade gracefully; alert."),
        ("Eval metric?", "nDCG@5, MRR on golden set comparing with/without rerank."),
        ("SDE3: rerank service?", "Stateless GPU pods; gRPC batch rerank; cache not useful (query-specific); SLO 80ms p99; autoscale on QPS; shadow test new model versions."),
    ),
)

# ── 11. model-serving-vllm ──────────────────────────────────────────
TOPICS["model-serving-vllm"] = dict(
    title="Model Serving (vLLM / Ollama)",
    nav="vLLM / Ollama",
    hero="Serve open-weight LLMs locally: vLLM for production throughput (PagedAttention, continuous batching), Ollama for dev simplicity, OpenAI-compatible APIs, GPU sizing, and quantization (AWQ/GPTQ).",
    tags=_tags(("vLLM", ""), ("Ollama", " orange"), ("PagedAttention", " green"), ("Quantization", " pink"), ("OpenAI API", " purple")),
    main_img="model-serving-vllm-main.png",
    main_cap="vLLM serving: OpenAI-compatible /v1/chat/completions → scheduler → PagedAttention KV cache → GPU workers. 8× Llama-3-8B throughput vs naive HF generate on same hardware.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","vllm","vLLM"),
        ("05","ollama","Ollama"),("06","quant","Quantization"),("07","gpu","GPU Sizing"),
        ("08","compare","vLLM vs Ollama"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p>Self-host Llama, Mistral, Qwen when data residency, cost at scale, or latency to cloud matters. <strong>vLLM</strong> for prod GPU serving; <strong>Ollama</strong> for laptop dev and quick pulls.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","PagedAttention"),("td","Non-contiguous KV cache blocks"),("td","vLLM core innovation")),
            (("td","Continuous batching"),("td","Add requests mid-batch"),("td","Higher GPU util")),
            (("td","AWQ/GPTQ"),("td","4-bit weight quantization"),("td","Small quality loss")),
            (("td","OpenAI compat"),("td","/v1/chat/completions"),("td","Drop-in for LC/OpenAI SDK")),
        ]))),
        ("api","01b","API Surface", card('<pre># vLLM OpenAI server\npython -m vllm.entrypoints.openai.api_server \\\n  --model meta-llama/Llama-3.1-8B-Instruct --tensor-parallel-size 1\n\n# Client (same as OpenAI)\nclient = OpenAI(base_url="http://gpu-host:8000/v1", api_key="dummy")\nclient.chat.completions.create(model="meta-llama/...", messages=[...])\n\n# Ollama\nollama run llama3.1\nollama serve  # localhost:11434</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Case"),("th","Self-host?"),("th","Alt")),
            (("td","Data cannot leave VPC"),("td","Yes vLLM"),("td","Azure private OpenAI")),
            (("td","Laptop prototype"),("td","Ollama"),("td","OpenAI API")),
            (("td","Peak GPT-4 reasoning"),("td","No"),("td","Closed API still wins")),
        ]))),
        ("architecture","03","Architecture", card("<p>Load balancer → vLLM replicas (1 GPU each or TP/PP multi-GPU) → model weights + KV cache RAM. Queue depth metric for autoscale.</p>")),
        ("vllm","04","Deep Dive: vLLM", diag("model-serving-vllm","vllm-zoom","vLLM PagedAttention: KV cache in fixed blocks, continuous batching scheduler") + card("<p>Flags: --max-model-len, --gpu-memory-utilization 0.9, --enable-prefix-caching for RAG system prompts.</p>")),
        ("ollama","05","Deep Dive: Ollama", diag("model-serving-vllm","ollama-zoom","Ollama local stack: pull model, Modelfile, REST API, single-user GPU") + card("<p>Modelfile for custom system prompt and parameters. Not multi-tenant prod server.</p>")),
        ("quant","06","Quantization", card("<p>AWQ 4-bit fits 70B on 2× A100 80GB. Benchmark perplexity/task accuracy vs FP16 on your eval before prod.</p>")),
        ("gpu","07","GPU Sizing", card("<p>8B FP16 ~16GB; 8B AWQ ~6GB; 70B AWQ ~40GB+. tensor-parallel-size splits layers across GPUs.</p>")),
        ("compare","08","vLLM vs Ollama", card(tbl([(("th",""),("th","vLLM"),("th","Ollama")),
            (("td","Target"),("td","Prod GPU cluster"),("td","Local dev")),
            (("td","Throughput"),("td","Very high"),("td","Moderate")),
            (("td","Setup"),("td","Complex"),("td","ollama pull")),
        ]))),
        ("production","09","Production & Ops", card("<ul><li>Health /v1/models; queue depth alerts</li><li>Rolling deploy with traffic drain</li><li>Prompt cache for shared system prompts</li></ul>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="openai-api-patterns.html">OpenAI API Patterns</a> (compat layer)</li><li><a href="embedding-models.html">Embedding Models</a> (tei for embed)</li><li><a href="langchain.html">LangChain</a> ChatOpenAI base_url</li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>Ollama in prod multi-tenant</li><li>OOM from max-model-len too high</li><li>No batching — low GPU util</li></ul>")),
    ],
    qa=_qa(
        ("vLLM vs HuggingFace generate?", "vLLM: PagedAttention + continuous batching = 5–20× throughput. HF generate: simple, low concurrency."),
        ("What is PagedAttention?", "KV cache stored in non-contiguous blocks like OS virtual memory — less fragmentation, more concurrent requests per GPU."),
        ("Ollama use cases?", "Local dev, demos, single-user apps. pull/run models in one command; OpenAI-ish API at :11434."),
        ("OpenAI-compatible why?", "Point LangChain/OpenAI SDK at vLLM with base_url — no code rewrite for self-host migration."),
        ("Quantization trade-off?", "AWQ/GPTQ 4-bit: ~1–3% quality drop, 4× memory savings. Eval on your tasks before prod."),
        ("GPU for Llama-3-8B?", "1× A10/L4 24GB FP16; or 1× T4 16GB with AWQ. Headroom for KV cache scales with concurrent users."),
        ("Tensor parallel?", "Split model across GPUs when single GPU VRAM insufficient — tensor-parallel-size 2 for 70B."),
        ("Prefix caching?", "vLLM caches identical prompt prefixes (system+RAG context) — big win for shared system prompts."),
        ("When still use OpenAI?", "Frontier reasoning, zero ops, burst scale without GPU cap. Hybrid: router sends easy to local, hard to GPT-4."),
        ("Embed serving?", "Use text-embeddings-inference (TEI) not vLLM for embed models — specialized batching."),
        ("Autoscale?", "K8s HPA on GPU queue depth and latency; cold start slow — min replicas > 0."),
        ("SDE3: private LLM platform?", "vLLM on K8s GPU pool; model registry; OpenAI gateway routing; quant pipeline; A/B model versions; cost per token internal chargeback; fallback to cloud API."),
    ),
)

# ── 12. llm-observability ───────────────────────────────────────────
TOPICS["llm-observability"] = dict(
    title="LLM Observability",
    nav="Observability",
    hero="Trace, evaluate, and debug LLM apps: LangSmith, Langfuse, OpenTelemetry, token/cost tracking, golden-set eval, online feedback, and production dashboards for RAG and agents.",
    tags=_tags(("LangSmith", ""), ("Langfuse", " orange"), ("Traces", " green"), ("Eval", " pink"), ("Cost", " purple")),
    main_img="llm-observability-main.png",
    main_cap="Observability stack: SDK wraps LLM/retriever/tool calls → trace spans (latency, tokens, I/O) → dashboard + alerts → eval harness regression on deploy.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","tracing","Tracing"),
        ("05","cost","Cost Tracking"),("06","eval","Eval Harness"),("07","feedback","Online Feedback"),
        ("08","tools","Tools Compare"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p>LLM apps fail silently — wrong retrieval, tool loops, prompt drift. <strong>Observability</strong> = traces (what happened), evals (is quality good), metrics (cost/latency). Required before prod launch.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","Trace"),("td","Tree of spans for one user request"),("td","Include retrieval + LLM + tools")),
            (("td","Span"),("td","Single operation with inputs/outputs"),("td","PII redaction policy")),
            (("td","Golden set"),("td","Labeled Q&A for regression eval"),("td","Update quarterly")),
            (("td","Feedback"),("td","Thumbs down / edit in UI"),("td","Close loop to dataset")),
        ]))),
        ("api","01b","API Surface", card('<pre># LangSmith — env vars auto-trace LangChain\nos.environ["LANGCHAIN_TRACING_V2"] = "true"\nos.environ["LANGCHAIN_PROJECT"] = "rag-prod"\n\n# Langfuse\nfrom langfuse.decorators import observe\n@observe()\ndef rag_pipeline(query: str):\n    ...\n\n# OpenTelemetry + custom spans\nwith tracer.start_as_current_span("retrieval") as span:\n    span.set_attribute("top_k", 20)\n    docs = retriever.invoke(query)</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Case"),("th","Obs stack?"),("th","Min")),
            (("td","Prod RAG/agent"),("td","Required"),("td","Langfuse/LangSmith")),
            (("td","One-off script"),("td","Optional"),("td","Print debugging")),
        ]))),
        ("architecture","03","Architecture", card("<p>App SDK → trace collector → storage (ClickHouse/Postgres/S3) → UI + alert rules → eval CI on golden set.</p>")),
        ("tracing","04","Deep Dive: Tracing", diag("llm-observability","tracing-zoom","Trace waterfall: root span RAG request → retrieval span → rerank → LLM generation with token counts") + card("<p>Tag spans: user_id hash, tenant, prompt_version, model. Link to <a href=\"langgraph.html\">LangGraph</a> node names.</p>")),
        ("cost","05","Cost Tracking", diag("llm-observability","eval-zoom","Dashboard: tokens in/out per model, cost USD, p99 latency, eval score trend over deploys") + card("<p>Aggregate usage tokens × price table per feature/tenant. Alert on 2× daily burn.</p>")),
        ("eval","06","Eval Harness", card("<p>CI runs golden 100 questions on deploy: recall@k, answer correctness LLM-judge, latency regression. See <a href=\"../systems/eval-harness.html\">Eval Harness</a>.</p>")),
        ("feedback","07","Online Feedback", card("<p>Capture thumbs down + optional correction → human review queue → add to golden set or fine-tune dataset.</p>")),
        ("tools","08","Tools Compare", card(tbl([(("th","Tool"),("th","Strength")),
            (("td","LangSmith"),("td","LangChain/LangGraph native, eval datasets")),
            (("td","Langfuse"),("td","Open source, self-host, prompt mgmt")),
            (("td","Arize Phoenix"),("td","Embeddings viz, retrieval debug")),
            (("td","Helicone"),("td","Proxy logging, cost gateway")),
        ]))),
        ("production","09","Production & Ops", card("<ul><li>PII scrub before export</li><li>Sample 100% errors, 10% success for volume</li><li>Alert: latency p99, error rate, eval drop</li></ul>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="openai-api-patterns.html">OpenAI API Patterns</a></li><li><a href="langgraph.html">LangGraph</a></li><li><a href="../systems/eval-harness.html">Eval Harness</a></li><li><a href="../systems/production-agent.html">Production Agent</a></li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>Log full prompts with secrets/PII</li><li>No eval CI — silent regressions</li><li>Traces without retrieval spans — can't debug RAG</li></ul>")),
    ],
    qa=_qa(
        ("What to trace in RAG?", "Query, retrieved chunk IDs+scores, rerank order, prompt template version, LLM output, tokens, latency per stage, user feedback."),
        ("LangSmith vs Langfuse?", "LangSmith: best LC integration, hosted. Langfuse: OSS self-host, prompt versioning, cheaper at scale."),
        ("OpenTelemetry for LLMs?", "Standard spans for any framework; GenAI semantic conventions emerging; export to Jaeger/Datadog."),
        ("How track cost?", "Log prompt/completion tokens per span; multiply by model price; aggregate by tenant/feature/day."),
        ("Golden set size?", "Start 50–100; grow from production failures. Run on every deploy blocking if score drops >5%."),
        ("LLM-as-judge eval?", "Model grades answer vs reference — fast but biased; calibrate with human sample."),
        ("Debug bad retrieval?", "Trace shows chunk IDs — inspect text in docstore; compare score distribution; check embed model version."),
        ("PII in traces?", "Redact emails/SSN regex; hash user_id; retention 30 days; GDPR delete API."),
        ("Sample rate?", "100% on errors; 5–20% success at high QPS; always log aggregate metrics."),
        ("Agent loop observability?", "One span per tool call; detect loops (same tool+args >3); max_steps alert."),
        ("Connect to incident response?", "Alert eval drop + error spike → rollback deploy; link trace_id in support tickets."),
        ("SDE3: observability platform for AI?", "Unified trace schema; Langfuse self-host; OTel collectors; golden CI gate; cost chargeback; feedback → dataset pipeline; dashboard per tenant SLO."),
    ),
)
