# ai_tech_content_p2.py — topics 2–12 for ai_tech_content.py

# ── 2. langchain ────────────────────────────────────────────────────
TOPICS["langchain"] = dict(
    title="LangChain",
    nav="LangChain",
    hero="Composable LLM framework: runnables (LCEL pipe), prompts, retrievers, tools, memory, and callbacks. The component layer most orchestrators (LangGraph, LlamaIndex integrations) build on.",
    tags=_tags(("LCEL", ""), ("Runnable", " orange"), ("Retrievers", " green"), ("Tools", " pink"), ("Callbacks", " purple")),
    main_img="langchain-main.png",
    main_cap="LangChain stack: Prompt | ChatModel | OutputParser as LCEL chain; retriever feeds context; tools bound via bind_tools; callbacks → LangSmith traces.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","lcel","LCEL"),
        ("05","retrievers","Retrievers"),("06","tools","Tools"),("07","memory","Memory"),
        ("08","callbacks","Callbacks"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p><strong>LangChain</strong> standardizes LLM app primitives: models, prompts, parsers, retrievers, tools — as composable <code>Runnable</code> objects. Use LCEL (<code>prompt | model | parser</code>) for DAG pipelines; use <a href=\"langgraph.html\">LangGraph</a> when you need cycles and checkpointing.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","Runnable"),("td","Unit with invoke/stream/batch"),("td","Everything is a Runnable")),
            (("td","LCEL"),("td","Pipe operator chains runnables"),("td","DAG only — no cycles")),
            (("td","Retriever"),("td","get_relevant_documents(query)"),("td","Wrap vector DB")),
            (("td","Tool"),("td","@tool decorated function + schema"),("td","Descriptions matter for routing")),
        ]))),
        ("api","01b","API Surface", card('<pre>from langchain_openai import ChatOpenAI\nfrom langchain_core.prompts import ChatPromptTemplate\nfrom langchain_core.output_parsers import StrOutputParser\n\nprompt = ChatPromptTemplate.from_messages([\n    ("system", "Answer from context: {context}"),\n    ("human", "{question}"),\n])\nchain = prompt | ChatOpenAI(model="gpt-4o-mini") | StrOutputParser()\nchain.invoke({"context": docs, "question": q})</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Case"),("th","LangChain?"),("th","Alt")),
            (("td","Simple RAG chain"),("td","Yes"),("td","Direct API")),
            (("td","ReAct agent loop"),("td","Maybe"),("td","LangGraph for control")),
            (("td","Multi-agent crew"),("td","Maybe"),("td","CrewAI")),
        ]))),
        ("architecture","03","Architecture", card('<pre>User Query -> Retriever (vector DB) -> format_docs\n          -> Prompt Template -> ChatModel -> Parser -> Answer</pre>')),
        ("lcel","04","Deep Dive: LCEL", diag("langchain","lcel-zoom","LCEL pipe: prompt | model | parser with parallel RunnableMap branches") + card("<p>LCEL supports <code>RunnableParallel</code>, <code>RunnableLambda</code>, fallbacks, and retries. Async via <code>ainvoke</code>.</p>")),
        ("retrievers","05","Deep Dive: Retrievers", card("<p>Wrap <a href=\"vector-databases.html\">vector DB</a> with <code>VectorStoreRetriever</code>; configure search_kwargs top_k. Multi-query retriever expands queries via LLM.</p>")),
        ("tools","06","Deep Dive: Tools", diag("langchain","tools-zoom","bind_tools on ChatModel: model emits tool_calls, ToolNode executes, results fed back") + card('<pre>llm_with_tools = llm.bind_tools([search, calculator])\n# Use with LangGraph ToolNode or create_react_agent</pre>')),
        ("memory","07","Deep Dive: Memory", card("<p>ChatMessageHistory, ConversationBufferWindowMemory (legacy). Production: store messages in Postgres; pass history in invoke input — don't rely on in-process memory.</p>")),
        ("callbacks","08","Deep Dive: Callbacks", card("<p>LangSmith auto-traces when env vars set. Custom BaseCallbackHandler for token logging. Tags: <code>chain.invoke(..., config={\"tags\": [\"prod\"]})</code>.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Pin package versions — LC breaks often</li><li>Prefer explicit chains over magic agents</li><li>LangSmith for eval regressions</li></ul>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="langgraph.html">LangGraph</a> nodes use LC runnables</li><li><a href="llamaindex.html">LlamaIndex</a> — overlapping scope</li><li><a href="../systems/rag-end-to-end.html">RAG End-to-End</a></li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>create_react_agent black box — hard to debug</li><li>Deprecated APIs in old tutorials</li><li>Memory in serverless (lost between requests)</li></ul>")),
    ],
    qa=_qa(
        ("What is LCEL?", "LangChain Expression Language: compose Runnables with | operator. prompt | model | parser. Supports sync/async/stream/batch uniformly."),
        ("LangChain vs LangGraph?", "LangChain = components and DAG chains. LangGraph = stateful graph with cycles, checkpointing, HITL. Use both: LC inside LangGraph nodes."),
        ("How wire a vector DB retriever?", "VectorStore.from_documents + as_retriever(search_kwargs={\"k\": 20}). In chain: {\"context\": retriever | format_docs, \"question\": RunnablePassthrough()}."),
        ("What are callbacks for?", "Hooks on chain start/end, LLM start/end, tool calls. LangSmith uses them for tracing; custom handlers for metrics."),
        ("Is LangChain still relevant in 2025?", "Yes as a component library; less as opaque agents. Teams use lc-core + langgraph + direct API where simpler."),
        ("How handle streaming in LCEL?", "chain.stream(input) yields partial dicts. For token stream: model streaming step or astream_events API."),
        ("Retriever vs VectorStore?", "VectorStore = storage + similarity_search. Retriever = Runnable interface for chains (includes MMR, compression, multi-query wrappers)."),
        ("Tool binding best practice?", "Clear descriptions, minimal parameters, validate args before side effects. bind_tools on model; execute in controlled ToolNode."),
        ("Memory in production?", "External store (Redis/Postgres) keyed by session_id; pass messages in state — not ConversationChain in-memory."),
        ("Version churn risk?", "Pin langchain-core, langchain-openai; integration tests on golden prompts; avoid deprecated chains in docs."),
        ("LangChain vs LlamaIndex?", "LangChain general orchestration + tools. LlamaIndex indexing/query focus. Overlap on RAG; many teams pick one primary."),
        ("SDE3: standardize LC across 10 teams?", "Internal template repo: LCEL RAG chain, LangGraph agent, shared retriever factory, LangSmith project per env, banned patterns list (deprecated agents)."),
    ),
)

# ── 3. crewai ───────────────────────────────────────────────────────
TOPICS["crewai"] = dict(
    title="CrewAI",
    nav="CrewAI",
    hero="Role-based multi-agent framework: Agents with backstory, Tasks with expected output, Crew orchestration (sequential, hierarchical). Fast path from idea to research-style agent teams.",
    tags=_tags(("Agents", ""), ("Tasks", " orange"), ("Crew", " green"), ("Hierarchical", " pink"), ("Delegation", " purple")),
    main_img="crewai-main.png",
    main_cap="CrewAI flow: define Agents (role, goal, tools) → Tasks (description, agent, context) → Crew(process=sequential|hierarchical) → kickoff() → consolidated output.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","agents","Agents"),
        ("05","tasks","Tasks"),("06","process","Process Types"),("07","tools","Tools"),
        ("08","vsgraph","vs LangGraph"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p><strong>CrewAI</strong> models teams of LLM agents with roles (Researcher, Writer, Manager). Tasks chain outputs; hierarchical process adds a manager agent that delegates. Great for prototypes; production often migrates to <a href=\"langgraph.html\">LangGraph</a> for HITL and checkpointing.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","Agent"),("td","role + goal + backstory + tools"),("td","Backstory shapes behavior strongly")),
            (("td","Task"),("td","description + expected_output + assigned agent"),("td","context=[prior tasks] for deps")),
            (("td","Crew"),("td","agents + tasks + process"),("td","kickoff() runs full workflow")),
            (("td","Process"),("td","sequential | hierarchical | consensual"),("td","Hierarchical needs manager_llm")),
        ]))),
        ("api","01b","API Surface", card('<pre>from crewai import Agent, Task, Crew, Process\n\nresearcher = Agent(role="Researcher", goal="Find facts", backstory="...", tools=[search])\nwriter = Agent(role="Writer", goal="Draft report", backstory="...")\n\nt1 = Task(description="Research {topic}", expected_output="Bullet facts", agent=researcher)\nt2 = Task(description="Write report", expected_output="Markdown report", agent=writer, context=[t1])\n\ncrew = Crew(agents=[researcher, writer], tasks=[t1, t2], process=Process.sequential)\nresult = crew.kickoff(inputs={"topic": "RAG trends"})</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Case"),("th","CrewAI?"),("th","Alt")),
            (("td","Research report crew"),("td","Yes"),("td","Manual LangGraph")),
            (("td","Production support bot"),("td","Maybe"),("td","LangGraph + HITL")),
            (("td","Single tool agent"),("td","No"),("td","One agent sufficient")),
        ]))),
        ("architecture","03","Architecture", card('<pre>Inputs -> Crew.kickoff -> Task1 (Agent A) -> Task2 (Agent B) -> Output\nHierarchical: Manager delegates tasks to workers</pre>')),
        ("agents","04","Deep Dive: Agents", diag("crewai","agents-zoom","Agent cards: role, goal, backstory, tools, allow_delegation flag") + card("<p>Each agent gets subset of tools. <code>allow_delegation=True</code> lets agent ask another agent (use sparingly — cost).</p>")),
        ("tasks","05","Deep Dive: Tasks", card("<p><code>expected_output</code> acts as implicit rubric. <code>context=[task1]</code> passes prior output. Async execution via <code>async_execution=True</code> on independent tasks.</p>")),
        ("process","06","Deep Dive: Process Types", diag("crewai","process-zoom","Sequential vs hierarchical: manager agent routes tasks to researcher and writer") + card("<p><strong>Sequential:</strong> fixed order. <strong>Hierarchical:</strong> manager_llm assigns dynamically. Cap total tasks at 5–8 for cost control.</p>")),
        ("tools","07","Deep Dive: Tools", card("<p>CrewAI tools wrap LangChain tools or custom BaseTool. Same security rules: validate args, read-only default, HITL on writes.</p>")),
        ("vsgraph","08","CrewAI vs LangGraph", card(tbl([(("th",""),("th","CrewAI"),("th","LangGraph")),
            (("td","Abstraction"),("td","High — roles/tasks"),("td","Low — nodes/edges")),
            (("td","HITL"),("td","Limited"),("td","interrupt_before")),
            (("td","Checkpoint"),("td","Basic"),("td","Postgres durable")),
        ]))),
        ("production","09","Production & Ops", card("<ul><li>Log full crew output + per-task traces</li><li>Timeout kickoff(); max_rpm on LLM</li><li>Migrate to LangGraph when need approvals</li></ul>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="../systems/multi-agent-orchestration.html">Multi-Agent Orchestration</a></li><li><a href="langgraph.html">LangGraph</a></li><li><a href="../systems/agent-architectures.html">Agent Architectures</a></li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>Crew for 2-step tasks — overkill</li><li>Unbounded delegation loops</li><li>Identical tools on all agents</li><li>No expected_output on tasks — vague results</li></ul>")),
    ],
    qa=_qa(
        ("What is CrewAI optimized for?", "Role-based multi-step workflows: research → analyze → write. Declarative agents/tasks faster than hand-rolling LangGraph for demos."),
        ("Explain Agent vs Task.", "Agent = persona + capabilities (tools). Task = unit of work with description and expected_output assigned to one agent. Tasks can depend on prior task outputs via context=[]."),
        ("Sequential vs hierarchical process?", "Sequential runs tasks in list order. Hierarchical adds manager agent that delegates tasks to workers dynamically — more flexible, less predictable."),
        ("How control cost?", "Limit agents/tools, cap kickoff timeout, use cheaper model for manager, disable allow_delegation unless needed, cache research task outputs."),
        ("CrewAI vs AutoGen?", "CrewAI: structured roles/tasks, simpler API. AutoGen: conversational agents, group chat patterns. Both less production-control than LangGraph."),
        ("Can CrewAI use local models?", "Yes via LangChain LLM wrappers (Ollama, vLLM OpenAI-compatible endpoint). See <a href=\"model-serving-vllm.html\">Model Serving</a>."),
        ("How test crew output quality?", "Golden inputs with rubric on expected_output; LLM-as-judge; human review sample; regression when prompt/backstory changes."),
        ("Tool security?", "Same as any agent: least privilege, validate JSON args, no arbitrary code exec without sandbox."),
        ("When migrate to LangGraph?", "Need HITL approval, durable checkpoint across days, custom routing logic, strict audit of each step."),
        ("Memory across kickoffs?", "Pass prior result in inputs or external DB; CrewAI doesn't replace session store for user chat."),
        ("Parallel tasks?", "async_execution=True on tasks without context dependency — runs in parallel where safe."),
        ("SDE3: design content pipeline with CrewAI.", "Researcher (web+RAG) → Fact-checker → Writer → Editor tasks; sequential; hierarchical manager for retry on failed fact-check; output to CMS API with HITL gate before publish (LangGraph for gate if Crew insufficient)."),
    ),
)

# ── 4. llamaindex ─────────────────────────────────────────────────
TOPICS["llamaindex"] = dict(
    title="LlamaIndex",
    nav="LlamaIndex",
    hero="Data framework for LLM apps: document loaders, node parsers, indices (vector, tree, keyword), query engines, and agents. Strongest when ingestion + retrieval complexity dominates.",
    tags=_tags(("Index", ""), ("Query Engine", " orange"), ("Nodes", " green"), ("Agents", " pink"), ("Ingestion", " purple")),
    main_img="llamaindex-main.png",
    main_cap="LlamaIndex pipeline: load documents → parse to Nodes → build VectorStoreIndex → QueryEngine (retriever + synthesizer) → response with source nodes.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","index","Indices"),
        ("05","query","Query Engine"),("06","ingest","Ingestion"),("07","agents","Agents"),
        ("08","vschain","vs LangChain"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p><strong>LlamaIndex</strong> focuses on getting data into LLM-ready form: loaders (PDF, Notion, SQL), chunking into <strong>Nodes</strong>, building <strong>Indices</strong>, and <strong>QueryEngines</strong> that retrieve + synthesize answers with citations.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","Node"),("td","Chunk + metadata (Document → Node)"),("td","Smallest indexed unit")),
            (("td","Index"),("td","Data structure over nodes"),("td","VectorStoreIndex most common")),
            (("td","QueryEngine"),("td","query → retrieve → synthesize"),("td","Wraps retriever + response synthesizer")),
            (("td","StorageContext"),("td","docstore + vector store + index store"),("td","Persist to disk for reload")),
        ]))),
        ("api","01b","API Surface", card('<pre>from llama_index.core import VectorStoreIndex, SimpleDirectoryReader\nfrom llama_index.core import Settings\nfrom llama_index.embeddings.openai import OpenAIEmbedding\n\nSettings.embed_model = OpenAIEmbedding(model="text-embedding-3-small")\ndocs = SimpleDirectoryReader("./data").load_data()\nindex = VectorStoreIndex.from_documents(docs)\nengine = index.as_query_engine(similarity_top_k=5)\nresponse = engine.query("What is our refund policy?")\nprint(response.source_nodes)  # citations</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Case"),("th","LlamaIndex?"),("th","Alt")),
            (("td","Complex doc ingestion"),("td","Yes"),("td","Custom pipeline")),
            (("td","Simple LCEL RAG"),("td","Maybe"),("td","LangChain sufficient")),
            (("td","Stateful agent graph"),("td","No"),("td","LangGraph")),
        ]))),
        ("architecture","03","Architecture", card('<pre>Sources -> Reader -> NodeParser -> Embeddings -> VectorStore\nQuery -> Retriever (top_k) -> ResponseSynthesizer -> Answer + Sources</pre>')),
        ("index","04","Deep Dive: Indices", diag("llamaindex","index-zoom","VectorStoreIndex backed by Pinecone/pgvector/Chroma with docstore for full text") + card("<p>Also: SummaryIndex, TreeIndex, KnowledgeGraphIndex. Production RAG almost always VectorStoreIndex + external vector DB.</p>")),
        ("query","05","Deep Dive: Query Engine", diag("llamaindex","query-zoom","Query engine: retriever top_k=20, postprocessor, compact/refine synthesizer modes") + card("<p><strong>Response modes:</strong> compact (single prompt), refine (iterative), tree_summarize. Add <code>SimilarityPostprocessor</code> cutoff.</p>")),
        ("ingest","06","Deep Dive: Ingestion", card("<p>LlamaHub loaders: 100+ connectors. IngestionPipeline for parallel extract/embed. Link <a href=\"../systems/document-ingestion.html\">Document Ingestion</a>.</p>")),
        ("agents","07","Deep Dive: Agents", card("<p>LlamaIndex agents use tools + query engines. For production control prefer <a href=\"langgraph.html\">LangGraph</a> with LlamaIndex retriever as tool.</p>")),
        ("vschain","08","vs LangChain", card("<p><strong>LlamaIndex:</strong> indexing, query engines, citation-first RAG. <strong>LangChain:</strong> general chains, broader ecosystem. Can combine: LI retriever in LC chain.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Persist index to <a href=\"pinecone.html\">Pinecone</a> not local disk</li><li>Version embed model in index name</li><li>Eval with golden queries on source_nodes recall</li></ul>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="../systems/rag-end-to-end.html">RAG End-to-End</a></li><li><a href="vector-databases.html">Vector Databases</a></li><li><a href="../systems/chunking-strategies.html">Chunking Strategies</a></li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>Default chunk size wrong for your docs</li><li>Not persisting — rebuild index every deploy</li><li>Ignoring source_nodes for eval</li></ul>")),
    ],
    qa=_qa(
        ("Node vs Document?", "Document = loaded file. Node = parsed chunk(s) with metadata — what gets embedded and indexed."),
        ("VectorStoreIndex vs loading vector DB directly?", "VectorStoreIndex wraps vector store + docstore + index struct. Use from_vector_store() to attach existing Pinecone/pgvector."),
        ("How get citations?", "response.source_nodes lists retrieved nodes with scores and metadata. Pass to UI; log for eval."),
        ("Query engine vs chat engine?", "QueryEngine: single Q&A. ChatEngine: multi-turn with memory. Production chat often custom history + query engine per turn."),
        ("LlamaIndex vs LangChain for RAG?", "LI stronger out-of-box ingestion/query/citations. LC more flexible orchestration. Many use LI for index + LC/LangGraph for agent layer."),
        ("Persist index?", "storage_context.persist() to disk; or write directly to managed vector DB for prod."),
        ("Custom node parser?", "SentenceSplitter with chunk_size/overlap; SemanticSplitter for embedding-based splits. Match <a href=\"../systems/chunking-strategies.html\">chunking</a> eval."),
        ("Hybrid search in LI?", "QueryFusionRetriever combines multiple retrievers; BM25 via Elasticsearch retriever + vector."),
        ("Agents in LlamaIndex?", "OpenAIAgent with query_engine_tools. Prefer LangGraph when need HITL/checkpointing."),
        ("Embedding model change?", "Full re-index; new collection name; never mix vectors."),
        ("Production scale?", "IngestionPipeline async; batch embed; external vector DB; query engine as stateless microservice."),
        ("SDE3: LI for enterprise doc RAG?", "IngestionPipeline: Notion+SharePoint loaders → semantic chunk → Pinecone namespace per tenant → QueryEngine with metadata filters → reranker → LangGraph agent wrapper; golden eval on source node recall."),
    ),
)

# ── 5. pinecone ─────────────────────────────────────────────────────
TOPICS["pinecone"] = dict(
    title="Pinecone",
    nav="Pinecone",
    hero="Fully managed vector database: serverless and pod indexes, namespaces, metadata filtering, sparse-dense hybrid, and upsert/query at scale without operating HNSW yourself.",
    tags=_tags(("Serverless", ""), ("Namespace", " orange"), ("HNSW", " green"), ("Metadata", " pink"), ("Managed", " purple")),
    main_img="pinecone-main.png",
    main_cap="Pinecone architecture: client upsert/query → serverless index (S3-backed segments + compute cache) → HNSW ANN → filtered top-k. p99 query ~20–40 ms at millions of vectors.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","serverless","Serverless"),
        ("05","metadata","Metadata Filters"),("06","hybrid","Hybrid Vectors"),("07","ops","Index Lifecycle"),
        ("08","compare","vs Others"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p><strong>Pinecone</strong> removes vector ops: no HNSW tuning, sharding, or RAM planning. Best when you want managed SLAs and multi-tenant SaaS RAG without a platform team. Compare <a href=\"pgvector.html\">pgvector</a> if already on Postgres.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","Index"),("td","Collection of vectors + metadata"),("td","Dimension fixed at create")),
            (("td","Namespace"),("td","Logical partition within index"),("td","Per tenant or embed version")),
            (("td","Serverless"),("td","Pay per usage; auto scale"),("td","Cold start on new indexes")),
            (("td","Pod"),("td","Dedicated capacity tier"),("td","Legacy; serverless preferred")),
        ]))),
        ("api","01b","API Surface", card('<pre>from pinecone import Pinecone\npc = Pinecone(api_key="...")\nindex = pc.Index("rag-prod")\n\nindex.upsert(vectors=[\n    {"id": "c1", "values": emb, "metadata": {"tenant": "acme", "page": 3}}\n], namespace="acme_v1")\n\nresults = index.query(\n    vector=query_emb, top_k=20, namespace="acme_v1",\n    filter={"tenant": {"$eq": "acme"}},\n    include_metadata=True,\n)</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Case"),("td","Pinecone?"),("th","Alt")),
            (("td","Multi-tenant SaaS RAG"),("td","Yes"),("td","Self-host Milvus")),
            (("td","Already on Postgres &lt;5M vec"),("td","Maybe not"),("td","pgvector")),
            (("td","Local dev"),("td","No"),("td","Chroma")),
        ]))),
        ("architecture","03","Architecture", card("<p>Serverless: vector data on object storage; query nodes load segments + HNSW into cache. Namespaces isolate tenants. See <a href=\"vector-databases.html\">Vector DB overview</a> for HNSW theory.</p>")),
        ("serverless","04","Deep Dive: Serverless", diag("pinecone","serverless-zoom","Serverless index: S3 segments, query compute cache, auto scale read units") + card("<p>Create with <code>cloud</code> and <code>region</code>. Monitor read units and storage billing.</p>")),
        ("metadata","05","Deep Dive: Metadata Filters", diag("pinecone","metadata-zoom","Metadata pre-filter DSL: $eq, $in, $gte on tenant_id and doc_type before ANN") + card("<p>Index metadata fields you filter on. Pre-filter avoids post-filter starvation.</p>")),
        ("hybrid","06","Hybrid Vectors", card("<p>Sparse-dense vectors for keyword+semantic in one query when enabled. Else dual-query in app layer + RRF. See <a href=\"../systems/hybrid-search.html\">Hybrid Search</a>.</p>")),
        ("ops","07","Index Lifecycle", card("<ul><li>Blue/green: new namespace for embed model v2</li><li>Delete by metadata filter for GDPR</li><li>Batch upsert 100–200 vectors per call</li></ul>")),
        ("compare","08","vs Others", card("<p>vs <a href=\"pgvector.html\">pgvector</a>: Pinecone = zero ops, higher $ at scale. vs <a href=\"weaviate.html\">Weaviate</a>: Pinecone simpler; Weaviate native BM25 hybrid.</p>")),
        ("production","09","Production & Ops", card("<ul><li>Monitor query latency p99, upsert lag</li><li>Rate limit client upserts</li><li>Never expose API key to browser</li></ul>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="vector-databases.html">Vector Databases</a></li><li><a href="../systems/rag-end-to-end.html">RAG End-to-End</a></li><li><a href="embedding-models.html">Embedding Models</a></li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>Wrong dimension at index create</li><li>One namespace for staging+prod</li><li>Post-filter instead of metadata filter</li><li>No embed version in namespace name</li></ul>")),
    ],
    qa=_qa(
        ("Why Pinecone over self-hosted?", "Zero HNSW ops, managed scaling, namespaces for multi-tenant. Trade-off: cost and less SQL join flexibility vs pgvector."),
        ("Serverless vs pod?", "Serverless: usage-based, auto scale, recommended for new projects. Pod: dedicated hardware, predictable perf for extreme QPS."),
        ("How multi-tenant?", "Namespace per tenant OR shared index + metadata filter tenant_id. Namespace = stronger isolation."),
        ("Metadata filter syntax?", "Mongo-style: {\"field\": {\"$eq\": \"val\", \"$in\": [...], \"$gte\": n}}. Only indexed metadata fields filter efficiently."),
        ("Upsert best practices?", "Batch 100–500; idempotent IDs (doc:chunk); include source text pointer in metadata; retry 429 with backoff."),
        ("Query latency tuning?", "top_k only what you need (20 before rerank); warm index with probe queries after deploy; co-locate region with app."),
        ("Embedding model change?", "New index or namespace; full re-embed; cutover after golden eval."),
        ("Hybrid in Pinecone?", "Sparse-dense when available; else BM25 in ES + vector in Pinecone + RRF in app."),
        ("Cost drivers?", "Storage (vectors×dim), read units (queries), write units (upserts). Compress metadata; prune stale namespaces."),
        ("Delete GDPR user?", "Delete by metadata user_id filter; verify docstore also purged."),
        ("Pinecone vs Weaviate?", "Pinecone simpler managed. Weaviate better if native hybrid GraphQL and self-host control needed."),
        ("SDE3: 10K tenants 100M vectors?", "Serverless index; namespace per tenant OR metadata tenant_id + strict pre-filter; ingest queue; embed service; reranker; per-tenant recall dashboards; blue/green re-index pipeline."),
    ),
)

# ── 6. weaviate ─────────────────────────────────────────────────────
TOPICS["weaviate"] = dict(
    title="Weaviate",
    nav="Weaviate",
    hero="Open-source vector database with native hybrid search (BM25 + vector), GraphQL API, modular embedders, and multi-tenancy. Self-host or Weaviate Cloud.",
    tags=_tags(("Hybrid", ""), ("GraphQL", " orange"), ("BM25", " green"), ("Multi-tenant", " pink"), ("HNSW", " purple")),
    main_img="weaviate-main.png",
    main_cap="Weaviate: GraphQL/REST API → hybrid query (alpha blends BM25 + vector) → HNSW index → filtered objects with properties. Self-host or managed cloud.",
    nav_items=_nav(
        ("01","what","What & Why"),("01a","concepts","Core Concepts"),("01b","api","API Surface"),
        ("02","when","When to Use"),("03","architecture","Architecture"),("04","hybrid","Hybrid Search"),
        ("05","graphql","GraphQL API"),("06","multitenancy","Multi-Tenancy"),("07","modules","Modules"),
        ("08","compare","vs Others"),("09","production","Production & Ops"),
        ("10","where","Where It Shows Up"),("11","pitfalls","Pitfalls"),("12","interview","Interview Q&A"),
    ),
    sections=[
        ("what","01","What &amp; Why", card("<p><strong>Weaviate</strong> shines when you need <strong>hybrid retrieval in one query</strong>, GraphQL flexibility, and optional server-side vectorization modules. Heavier ops than Pinecone if self-hosted.</p>")),
        ("concepts","01a","Core Concepts", card(tbl([(("th","Term"),("th","Definition"),("th","Gotcha")),
            (("td","Class"),("td","Schema collection like a table"),("td","Define properties + vectorizer")),
            (("td","Hybrid"),("td","alpha * dense + (1-alpha) * BM25"),("td","Tune alpha on dev set")),
            (("td","Tenant"),("td","Multi-tenancy activation per class"),("td","Isolated tenant shards")),
        ]))),
        ("api","01b","API Surface", card('<pre># GraphQL hybrid query\n{\n  Get {\n    Document(\n      hybrid: { query: "refund policy", alpha: 0.5 }\n      limit: 20\n      where: { path: ["tenantId"], operator: Equal, valueText: "acme" }\n    ) {\n      content\n      _additional { score distance }\n    }\n  }\n}</pre>')),
        ("when","02","When to Use / When NOT", card(tbl([(("th","Case"),("th","Weaviate?"),("th","Alt")),
            (("td","Hybrid BM25+vector native"),("td","Yes"),("td","Dual ES+pgvector")),
            (("td","Zero ops vector"),("td","No"),("td","Pinecone")),
            (("td","SQL joins with orders"),("td","No"),("td","pgvector")),
        ]))),
        ("architecture","03","Architecture", card("<p>Go binary cluster; replication; HNSW + inverted index for BM25. Modules call OpenAI/Cohere for vectorization at ingest.</p>")),
        ("hybrid","04","Deep Dive: Hybrid Search", diag("weaviate","hybrid-zoom","Hybrid alpha slider: 0=BM25 only, 1=vector only, 0.5=fusion default starting point") + card("<p>Start alpha=0.5; grid search {0.3,0.5,0.7} on golden Recall@5.</p>")),
        ("graphql","05","Deep Dive: GraphQL API", diag("weaviate","graphql-zoom","GraphQL Get query with where filter, hybrid block, and _additional score metadata") + card("<p>Also REST v1 objects API. GraphQL good for flexible property selection.</p>")),
        ("multitenancy","06","Multi-Tenancy", card("<p>Enable multiTenancyConfig on class; each tenant isolated. Auto-tenant creation on ingest optional.</p>")),
        ("modules","07","Modules", card("<p>text2vec-openai, reranker-cohere, generative-openai. Can vectorize at ingest server-side — still version embed model carefully.</p>")),
        ("compare","08","vs Others", card("<p>vs <a href=\"pinecone.html\">Pinecone</a>: more hybrid-native, more ops. vs <a href=\"pgvector.html\">pgvector</a>: no SQL joins but better hybrid DX.</p>")),
        ("production","09","Production & Ops", card("<ul><li>K8s helm chart; 3+ node replication</li><li>Backup S3; monitor recall/latency</li><li>Weaviate Cloud for managed</li></ul>")),
        ("where","10","Where It Shows Up", card('<ul><li><a href="vector-databases.html">Vector Databases</a></li><li><a href="../systems/hybrid-search.html">Hybrid Search</a></li><li><a href="rerankers.html">Rerankers</a></li></ul>')),
        ("pitfalls","11","Pitfalls", card("<ul><li>Self-host without K8s expertise</li><li>Wrong alpha for query type</li><li>Module embed model drift vs query embed</li></ul>")),
    ],
    qa=_qa(
        ("Weaviate's killer feature?", "Native hybrid search in one API call — BM25 + vector with alpha tuning. Avoids dual-system fusion code."),
        ("What is alpha in hybrid?", "Weight between dense (1) and sparse (0). 0.5 default; SKU queries lower alpha (more BM25)."),
        ("Self-host vs cloud?", "Self-host: K8s, replication, you patch. Cloud: managed backups, scaling — like Pinecone model."),
        ("GraphQL vs REST?", "GraphQL flexible for nested queries and property pick. REST simpler for CRUD scripts."),
        ("Multi-tenancy model?", "Tenant shards per class; query must specify tenant. Strong isolation for SaaS."),
        ("Server-side vectorization?", "Modules embed at ingest — ensure query uses same module/model or bring own vectors."),
        ("Weaviate vs Pinecone?", "Weaviate: hybrid-native, self-host option. Pinecone: simpler managed, less ops."),
        ("Weaviate vs pgvector?", "Weaviate: hybrid + GraphQL. pgvector: SQL joins + ACID in Postgres."),
        ("Reranking integration?", "reranker-cohere module or external <a href=\"rerankers.html\">cross-encoder</a> after hybrid top-20."),
        ("Index rebuild?", "Re-import with new vectorizer; new class version; blue/green cutover."),
        ("Ops monitoring?", "Prometheus metrics; query latency; object count; hybrid alpha A/B in logs."),
        ("SDE3: hybrid RAG on Weaviate?", "Class Document with text property + tenantId; multiTenancy; hybrid alpha tuned per query router; retrieve 20 → Cohere rerank → 5 to LLM; eval Recall@5 weekly."),
    ),
)

# Continue with pgvector, chroma, embedding-models, rerankers, vllm, observability
exec(compile(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)), 'ai_tech_content_p3.py')).read(), 'ai_tech_content_p3.py', 'exec'))
