classDiagram
    class Course {
        -String courseId
        -String title
    }
    class Student {
        -String studentId
        -String name
    }
    class Enrollment {
        -String enrollmentId
    }
    class LearningPlatformService {
        <<interface>>
        +createCourse()
        +enrollStudent()
    }
    LearningPlatformService --> Course
    LearningPlatformService --> Student
    LearningPlatformService --> Enrollment
