classDiagram
    class Task {
        -String taskId
        -TaskStatus status
    }
    class Board {
        -String boardId
    }
    class TaskManagementService {
        <<interface>>
        +createTask()
        +updateStatus()
    }
    TaskManagementService --> Task
    TaskManagementService --> Board
    Board --> Task
